### ISSUE TITLE
IS-05 "Interaction with Node API" independence of tests

### ISSUE THREAD

**Issue by WaterPug** [AMWA-TV/nmos-testing#116]
Considering that the uninitialized state of a sender or receiver resource will return "auto" as value for the destination port when doing a GET on the staged parameters, tests 7, 8, 9, 10 and 11 will fail if tested individually and in a uninitialized state. This is the case since in IS0502Test.py, the activate_check_parked function will do a GET on the staged and the active parameters and compare the destination ports to make sure they are identical. This will inevitably fail, unless tests 5 and 6 are executed prior to these tests (or the value of the destination port in the staged parameters was already modified to something other than auto and applied to the active parameters before this test) since the tests 5 and 6 will modify the destination port and make sure the value is different than auto.

Ideally these tests should not depend on the state of the staged parameters and should make sure to modify the destination port in the staged parameters, and apply the settings to the active parameters, before comparing the staged and active values.

Not critical, but it could cause confusion when trying to debug an individual test case. :^)

**Comment by andrewbonney** [comment]
Thanks for the detailed report. We'll take a look.

**Comment by andrewbonney** [comment]
@WaterPug This should be fixed now. If you find that's not the case please feel free to re-open the bug.
