### ISSUE TITLE
"Run" button does not reactivate after executing a single test

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#128]
I ran an IS-04/-05 interaction test (test 08, to be precise). I then clicked my browser's back button because I wanted to run all the tests, but the button at the bottom of the interface never went back to "Run" but was stuck on "Executing test". Running all the tests doesn't cause this misbehavior.

**Comment by garethsb-sony** [comment]
FWIW, I couldn't repro in either Chrome or IE. In both cases, Test Selection reset to "all".

**Comment by andrewbonney** [comment]
I can't seem to replicate either. Can you make this happen consistently @billt-hlit? If so can you provide any more info on browsers etc?

**Comment by billt-hlit** [comment]
Right. Anyhow, seems to have only been Firefox on Linux. Jasper's change takes care of it in any case.

**Comment by jasperpeeters** [comment]
> I can't seem to replicate either. Can you make this happen consistently @billt-hlit? If so can you provide any more info on browsers etc?

I also have this with Firefox 65.0 on a Ubuntu 18.04.02 and a Firefox 65.0.1 on a current Antergos system. No problems with Chrome.

I have this when I just click the "Back" (history) button after executing any (single or all) test.. The run button is still just deactivated. However, to rerun a test I just hit `F5` on the Result page resending the HTTP request which just works fine. 

I understand the big disadvantage of my PR that this removes the pre-filled ip+port from the textboxes.

**Comment by andrewbonney** [comment]
Just tried out the PR and don't have a problem with it, but yes the removal of the boxes (and dropdown) presets is a little annoying. Could we resolve this via local storage or similar as-per the answers to https://stackoverflow.com/questions/37270089/keep-form-data-with-back-button

**Comment by jasperpeeters** [comment]
Added now (see https://github.com/AMWA-TV/nmos-testing/pull/131#issuecomment-467835291)
