### ISSUE TITLE
Module 'websocket' has no attribute 'WebSocketApp' 

### ISSUE THREAD

**Issue by SerebryanskiySergei** [AMWA-TV/nmos-testing#133]
Hi all!

In the process of testing RDS using "IS-04 Registry APIs Tests" I've faced a following error:

Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. module 'websocket' has no attribute 'WebSocketApp' 

```
* Running test_31
Traceback (most recent call last):
  File "/opt/AMWA-TV/nmos-testing/GenericTest.py", line 102, in execute_tests
    self.result.append(method())
  File "/opt/AMWA-TV/nmos-testing/IS0402Test.py", line 886, in test_31
    websockets[resource] = WebsocketWorker(r.json()["ws_href"])
  File "/opt/AMWA-TV/nmos-testing/TestHelper.py", line 97, in __init__
    self.ws = websocket.WebSocketApp(ws_href,
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
192.168.59.213 - - [15/Feb/2019 13:19:15] "POST / HTTP/1.1" 200 -
```

PS. All other tests passed.

**Comment by garethsb-sony** [comment]
That's strange. What version of the "websocket-client" module do you have installed?
E.g.
```
py -m pip show websocket-client
```

**Comment by SerebryanskiySergei** [comment]
I've websocket 0.2.1 installed on the machine with tests suite.

**Comment by garethsb-sony** [comment]
I don't think that's the right module. You need https://pypi.org/project/websocket-client/, not https://pypi.org/project/websocket/.

To get all the required modules you should be able to use:

```
py -m pip install -r requirements.txt
```

**Comment by andrewbonney** [comment]
Hopefully this confusion has been resolved via https://github.com/AMWA-TV/nmos-testing/pull/136

**Comment by SerebryanskiySergei** [comment]
thanks for help, the problem was solved!

**Comment by congzhengLei** [comment]
Can you tell me how you solved it?

**Comment by andrewbonney** [comment]
The solution is here:

> I don't think that's the right module. You need https://pypi.org/project/websocket-client/, not https://pypi.org/project/websocket/.

**Comment by clearhead09** [comment]
I'm also having this problem. I have tried installing, uninstalling etc both the websocket and the websocket-client.

I am currently using PyCharm and my Mac says the correct files are located in Anaconda's site files directory. 

Do I need to connect the webserver client to the project in PyCharm?

**Comment by andrewbonney** [comment]
I'm afraid I'm not familiar with your IDE. I'd recommend testing this outside of the IDE first if you can to confirm any problems on your system. Running `python` from the command line and then manually importing/using the module should prove whether you have the correct one installed.

**Comment by ArchimedCharbon** [comment]
I had the same problem, after uninstalling websocket and websocket-client, I only reinstalled websocket-client and now everything is fine.

So:
`sudo pip3 uninstall websocket`
`sudo pip3 uninstall websocket-client`

And then: 
`sudo pip3 install websocket-client`

**Comment by tiusoro** [comment]
hello guys,

Having issues activating a virtual environment on my vscode.
PS C:\Users\naco40008\RSIBot\python_env\env1\scripts> source activate
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the       
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ source activate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\naco40008\RSIBot\python_env\env1\scripts> activate
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ activate
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Also when i run my bot.py file it comes up with the error:
 ws = websocket.WebsocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message)
AttributeError: module 'websocket' has no attribute 'WebsocketApp'

Am new to this and just learning and came up a tutorial on how to build a crypto bot and have tried everything as explained in the tutorial but seems to hit the block path.
I would really appreciate your help on this. 
Thank you.

**Comment by tiusoro** [comment]
Question 2 has been resolved. I deleted the line code and retyped it again using intellisense and the websense app was now created. 

Still having issues with creating a virtual environment.

Thank you

**Comment by dallastownsend** [comment]
So i tried all of these things i have the lastest websocket-client updated but i am still getting the same error.

**Comment by garethsb** [comment]
Did you uninstall `websocket` as well as installing `websocket-client`? What exact messages are you getting?

**Comment by dallastownsend** [comment]
> Did you uninstall `websocket` as well as installing `websocket-client`? What exact messages are you getting?


Yes i have websocket-client and do not have websocket installed

File "c:\Users\dalla\OneDrive\Desktop\ALPCA-main\WS.py", line 63, in <module>
    ws = websocket.WebSocketApp(socket, on_open=on_open, on_message=on_message, on_close=on_close)
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
PS C:\Users\dalla\OneDrive\Desktop\ALPCA-main>

**Comment by garethsb** [comment]
What is _ALPCA-main\WS.py_? I don't recognise that code as part of _AMWA-TV/nmos-testing_...
