### ISSUE TITLE
IS-05 v1.1 testing: uncaught exception: cannot find file \\receiver_transport_params_ext.json

### ISSUE THREAD

**Issue by jwpwh** [AMWA-TV/nmos-testing#134]
When running the test suite for IS-05 Connection Management API with API Version v1.0, there are no errors. When running the test suite with v1.1, I see 2 errors and it is not clear that they are related to my configuration.  The test report asks that the traceback from the terminal be reported here.

Tests failing:  test_15 and test_16.

Test_15 text:  Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. <urlopen error [WinError 2] The system cannot find the file specified: '\\sender_transport_params_ext.json'>

test_16 text: Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. <urlopen error [WinError 2] The system cannot find the file specified: '\\receiver_transport_params_ext.json'>

Traceback from the terminal is in attached file.
[IS05_v1_1_terminal_traceback.txt](https://github.com/AMWA-TV/nmos-testing/files/2877127/IS05_v1_1_terminal_traceback.txt)

The file names in the error messages do seem to be present in nmos-testing\cache\is-05\APIs\schemas

**Comment by jwpwh** [comment]
I was apparently using the wrong websocket package so I uninstalled the websocket package, installed the websocket-client package, and reran the test. The result was the same.

**Comment by andrewbonney** [comment]
I suspect this is to do with Windows/Linux file paths. We've had various issues in this area which we've resolved via a 'load_resolved_schemas' method, but this doesn't appear to be used everywhere yet. Could you see if https://github.com/AMWA-TV/nmos-testing/pull/137 fixes the issue for you? If so I'll do the remaining work to ensure the same approach is used throughout the code.

**Comment by jwpwh** [comment]
The code in #137 seems to fix the issue. The 2 uncaught exceptions I was seeing no longer appear and the tests indicate Pass instead of fail.

Thanks for the quick response.

**Comment by andrewbonney** [comment]
Thanks for checking. I'll add the remaining fixes and then look at getting it merged in.
