### ISSUE TITLE
External dependencies missing websocket and git command

### ISSUE THREAD

**Issue by jwpwh** [AMWA-TV/nmos-testing#135]
The external dependencies listed in the ReadMe.md seems to be missing 2 dependencies:

* The python package websocket is needed
* A git command needs to be installed and in the path. (on windows git.exe)

**Comment by garethsb-sony** [comment]
The correct list of dependencies are in requirements.txt. It's https://pypi.org/project/websocket-client/ not https://pypi.org/project/websocket/ that is needed. README.md ought to have been updated at the same time in commit caa9a995db807aa848eb200500f527f437263077.

**Comment by jwpwh** [comment]
Maybe the ReadMe.md file should just refer to requirements.txt so 2 places don't need to be kept in sync. The list is also in setup.py so maybe the count is 3 instead of 2.

**Comment by jwpwh** [comment]
Now I see the other updates and see that others thought the same thing.
