### ISSUE TITLE
IS-05 Interaction with Node API Test request: Verify that IS-05 API path matches IS-04 Device's "controls" entries

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#139]
I ran into a small problem today via the VPN to the Houston workshop: My "href" in "controls" entries for my IS-04 devices was missing its trailing slash, which confused at least one control system. Oops.

Ideally, the test suite would use the href parameter itself rather than expecting the person running the test to provide it, and could verify the URL at the same time.

**Comment by garethsb-sony** [comment]
As discussed offline, the [IS-05 v1.0.1 APIs - Approach to trailing slashes](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.1/docs/2.0.%20APIs.md#urls-approach-to-trailing-slashes) documentation (and same in IS-04) clarifies that the 'primary' path is the one without the slash. However, it is the case that several examples do have a trailing slash, so this needs another review.

My feeling is probably that when this URL needs to be appended to, it's the client's job to work out whether to add a slash or not.

**Comment by andrewbonney** [comment]
@garethsb-sony got to this just before I pressed comment :)

Hmm, I'm not sure there's an issue with your implementation, it sounds like the control system might need an update regarding URL handling.

The test suite does actually already test this as part of test_02 in the IS-05/IS-04 tests. We ask the user to enter the address for both IS-04 and IS-05 so we can ensure through this sort of check that things match up to expectations. The URL listed in the 'href' attribute is then compared with what was entered by the user, but crucially the trailing slashes are stripped from each before the comparison takes place. URLs without trailing slashes must be supported to ensure consistency, but many of the examples show a trailing slash for historic reasons. Provided the implementation correctly provides a 3xx redirect however the trailing slash version is fine to appear in the controls href.

**Comment by garethsb-sony** [comment]
> Provided the implementation correctly provides a 3xx redirect however the trailing slash version is fine to appear in the controls href.

I think the issue here was probably that the control system just took the value and immediately appended "single/senders" or somesuch to it, assuming that the value finished with a slash.

**Comment by andrewbonney** [comment]
Yeah, use of URL parsing/processing libraries very much encouraged for these cases, or at the very least trim trailing slashes before doing this sort of thing and explicitly re-add one.

**Comment by garethsb-sony** [comment]
>at the very least trim trailing slashes before doing this sort of thing and explicitly re-add one.

That works

>  use of URL parsing/processing libraries very much encouraged for these cases

I'm not sure about that... as I'm pretty sure the RFC says that resolving the relative URL "bar/baz" for the base URL ".../foo/" produces something different than for the base URL ".../foo".

**Comment by andrewbonney** [comment]
Should we close this one given it's being discussed against a spec now? As far as I know the test suite already does all it can in this regard.

**Comment by billt-hlit** [comment]
I still have lingering concerns about this suite asking the user to enter the URL for the IS-05 API. In particular, if different Devices are using different URLs, it seems like several tests, including test_02, are going to incorrectly fail.

That said, that probably should be addressed in a separate bug ticket.

**Comment by garethsb-sony** [comment]
> Devices are using different URLs, it seems like several tests, including test_02, are going to incorrectly fail.

That's true. Good point.

> That said, that probably should be addressed in a separate bug ticket.

Worth doing.
