### ISSUE TITLE
Add testing of HTTPS access to APIs

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#146]
Based upon BCP-003-01. Should provide the means to test that TLS is implemented (with assistance from external tools). Should also ensure that URLs used within the API responses (including headers) correctly indicate HTTPS and DNS names as required.

**Comment by garethsb-sony** [comment]
Possible tests...

mDNS advertisements - api_proto

Node API /self - href, api.endpoints.scheme, services.href

Node API /devices - controls.href

Node API /senders - manifest_href

Query API - Link response headers

Registration API - Location response headers

**Comment by garethsb-sony** [comment]
Also...

Query API /subscriptions - secure (default value added when not specified in POST), ws_href

**Comment by garethsb-sony** [comment]
Also... WARNING or FAIL if Node tries to connect to Registration API via SSL or TLS v1.0/v1.1? Think that could be a separate test though!

**Comment by andrewbonney** [comment]
This one may take a while, but I'm going to start adding a few things to a draft PR. We can either choose to merge them in gradually (given that they'll only be enabled via config for now) or wait until they're more feature complete.

**Comment by garethsb-sony** [comment]
Nope, really happy to merge piece by piece. Any testing is better than no testing! Thanks, Andrew.

**Comment by garethsb-sony** [comment]
I'm unable to have a look at this or your other active PR on advanced queries until next week, but @simonlo-sony and @KevinTao-Sony might want to have a look at both of these. 😉

**Comment by andrewbonney** [comment]
Note to self: Whilst the test tool intentionally asks for IP addresses in order to ensure DNS-SD records can be resolved, the best practice for TLS is to use hostnames. It may be necessary to permit these, but to perform a resolution step within the test suite when checking these against IP addresses returned via mDNS and similar.

**Comment by andrewbonney** [comment]
I'm going to call the first PR done subject to any review comments. There are various other TODOs which I'll tackle via additional PRs, including:

* Checking of hostnames vs. IPs (and whether they match the certificate CN/SANs)
* Ensuring the test suite knows about the trust store to avoid testing with requests certificate verification turned
* HTTPS support for the mock Node/Registry (which will probably fix the HTTP/1.1 issue at the same time.
* Addition of a test which calls out to testssl.sh as part of the auto_ set in order to check cipher suites etc.

**Comment by andrewbonney** [comment]
I'm going to look at testing the specifics of BCP003-01 in a separate test set. Some of the calls to testssl.sh take a long time, and as all NMOS APIs may be hosted on the same port there's probably no reason to test them everywhere.

**Comment by garethsb-sony** [comment]
Another note to selves 😉

> * Checking of hostnames vs. IPs (and whether they match the certificate CN/SANs)

PR #161 tests scheme in all these properties but checking for hostname rather than IP addresses will be part of an additional PR:

> Node API /self - href, api.endpoints.host, services.href
> Node API /devices - controls.href
> Node API /senders - manifest_href
> Query API - Link response headers
> Registration API - Location response headers

**Comment by andrewbonney** [comment]
Another note from the first PR. Tests which cross between IS-04 and another IS should ensure that both instances are using matching protocols. For example, IS0502 testing of the Device 'controls' should be updated to check the protocols match what is under test.

**Comment by simonlo-sony** [comment]
> * HTTPS support for the mock Node/Registry (which will probably fix the HTTP/1.1 issue at the same time.

In addition to these HTTPS mocks, will also need a mock Sender for `IS0401Test.test_13`.

**Comment by andrewbonney** [comment]
Remaining items...
- [ ] Add HTTPS support for mock Node and Registry
- [ ] Check if IP/hostname is used in certificate during auto_ tests and WARN if the former
- [ ] Permit a hostname to be entered in the homepage as an alternative to an IP (requires mDNS check updates)
- [ ] Add a CA and testing certificate (or method to generate) to the test suite
- [ ] Re-enable certificate verification in requests/websockets once trust can be established
- [ ] Check whether HSTS is enabled as-per BCP-003-01

**Comment by garethsb-sony** [comment]
We're having some problems with the BCP-003-01 PR. It looks like the cipher names in the "finding" from OpenSSL 1.1.0g on an Ubuntu box here are formatted differently than expected - aligned with spaces rather than tabs?

**Comment by andrewbonney** [comment]
Ok. I'll see if the separation can be performed using a generic whitespace character regex or something. The JSON output isn't perfect for parsing in all cases unfortunately.

**Comment by garethsb-sony** [comment]
> Add HTTPS support for mock Node and Registry

FWIW, @simonlo-sony has done some work on this. One of the things we've found is that `IS0401Test.test_05` is failing with "Heartbeats are too frequent." because the Node is *issuing* heartbeats at 5 second intervals, and the mock Registry is timing *processing* of heartbeats, and the first heartbeat is subject to ~2 seconds delay, presumably due to the setting up of the TLS connection.

**Comment by garethsb-sony** [comment]
> Node API /self - href, api.endpoints.host, services.href
> Node API /devices - controls.href
> Node API /senders - manifest_href
> Query API - Link response headers
> Registration API - Location response headers
> Query API /subscriptions - ws_href

Would a simple check for all the URLs just be that if they are 'https' or 'wss' ones they have a host name not an IP address? Would that deal with the fact that some controls and services may be insecure or refer to different hostnames than the one entered into the webapp UI?

That would just leave Node api.endpoints.host, which should be a hostname if api.endpoints.protocol is "https".

WARNING on failure?

**Comment by garethsb-sony** [comment]
> Another note from the first PR. Tests which cross between IS-04 and another IS should ensure that both instances are using matching protocols. For example, IS0502 testing of the Device 'controls' should be updated to check the protocols match what is under test.

`IS0502Test. test_02_device_control_present` seems to check for a matching URL. Is that enough?

**Comment by andrewbonney** [comment]
> Would a simple check for all the URLs just be that if they are 'https' or 'wss' ones they have a host name not an IP address? Would that deal with the fact that some controls and services may be insecure or refer to different hostnames than the one entered into the webapp UI?

Yes, I think that would be a good start. I think we should also call out if the user enters an IP address rather than a hostname into the web UI (or from the command line) when HTTPS mode is on. Perhaps this should also be a warning. Provided that's in place then simply ensuring a match in IS0502 test_02 is probably enough.

I'd still be keen to ensure that the host entered into the UI matches one of the available options in cases where there are multiple choices such as Node endpoints.

**Comment by garethsb-sony** [comment]
Now just these left to check that they use hostnames not IP addresses with 'https' and 'wss' URLs...

> Query API - Link response headers
> Registration API - Location response headers
> Query API /subscriptions - ws_href

**Comment by garethsb-sony** [comment]
> Query API - Link response headers
> Registration API - Location response headers
> Query API /subscriptions - ws_href

Those are done in #253.

But I've thought of one more... :sob:

Connection API - Location header in a 307 temporary redirect response to GET /transportfile

Like other places, it should match scheme and an 'https' URL should have a hostname not IP address.

**Comment by garethsb-sony** [comment]
Since NMOS specs also allow 301 redirects e.g. for [URLs with trailing slashes](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/2.0.%20APIs.md#urls-approach-to-trailing-slashes), I think the best thing to do would be just to update `TestHelper.do_request` to check consistent URL schemes in `response.history`.

I'll make a PR for that, and then I'm call this monster 👾 killed.
