### ISSUE TITLE
Interactive test harness improvements

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#150]
Coincidentally to Andrew's work on PR #147 to enable non-interactive testing (and Jasper's PR #131 to store session data) we've been looking at enhancing the interactive runner. This would allow the user to select a few test cases from a suite rather than just all or one, and to make re-running tests, or e.g. just those that failed, easier.

Animated gif demo (I hope!):

![testing-suite](https://user-images.githubusercontent.com/31761158/53751496-4b46ca80-3ea4-11e9-9b42-58d7ee1db92f.gif)

**Comment by andrewbonney** [comment]
Looks good, particularly the re-running capability.
