### ISSUE TITLE
Support for IS-07 senders / receivers in IS0501 Test

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-testing#152]
The IS0501 test is implemented against RTP transport typed transceivers. As with v1.1 IS-07 senders / receivers with mqtt and websockets are added, this must also be supported. For those I run currently into fails.

Opening this issue as a placeholder / reminder.

**Comment by andrewbonney** [comment]
This should now work for MQTT but not yet for WebSockets
