### ISSUE TITLE
Feature Request: pagination tests

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#17]
There are edge cases for Query API pagination, including the cursors themselves but also correct encoding of the Link header, especially when RQL queries are involved.

(I'll being trying to contribute some of these feature requests I'm adding now!)

**Comment by andrewbonney** [comment]
@garethsb-sony can this one be closed?

**Comment by garethsb-sony** [comment]
Yes. The encoding of RQL queries is even slightly more tricky than the simple example I just added before merging #115, but I'll remember that when we get around to doing better RQL testing.

By the way, I've been meaning to ask you - does IS0401Test test_16 mean that test_06 is redundant?

**Comment by andrewbonney** [comment]
Yes I think it probably does. test_06 was always a drop-in from the paper checklists and encompassed checking of many things. We don't check that Nodes handle every possible 4xx/5xx code as yet, but I think the main ones are covered so this could probably be removed to avoid confusion.
