### ISSUE TITLE
Feature Request: Query API WebSocket tests

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#19]
Query API WebSocket tests would be great... and if we can share tooling with Event & Tally tests, so much the better.

(I'll being trying to contribute some of these feature requests I'm adding now!)

**Comment by andrewbonney** [comment]
Can we close this one on the basis that we now have some tests, and more advanced testing is noted in https://github.com/AMWA-TV/nmos-testing/issues/30?

**Comment by garethsb-sony** [comment]
Absolutely. :-)
#66, #106
