### ISSUE TITLE
Cryptic "uri" message running IS-05 tests

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#194]
When I attempt to run the IS-05 Connection Management "auto" tests, I get the cryptic message "Error: 'uri'" and am brought back to the "NMOS Test" front page. A little bisecting lead me to the @andrewbonney's commit 9df1dc8a510c1e65504401db56bca8f6454dfed1 from the 6th of March as the oldest one that makes this error occur. Reverting that commit at the top of the master branch makes the error go away.

Any ideas? Thanks.

**Comment by garethsb-sony** [comment]
The 'uri' format checker needs the 'rfc3987' python module. That has been added to requirements.txt, but if you've kept the same codebase since before then and not rerun the install that might explain it?

**Comment by billt-hlit** [comment]
Ah, yes, your diagnosis is spot-on, Gareth. I'd been maintaining the requirements manually because ubuntu provides a portion of them as OS packages.

Still, was expecting an ImportError message with a name of the missing module, but the stack walkback I received from didn't even hint that a missing module was the problem.. I'll leave this ticket open in hopes that someone will be inspired to make the root cause a little more obvious.

Thanks,
Bill

**Comment by andrewbonney** [comment]
I've had a quick look at this one, but unfortunately it's not straightforward as the package names in 'requirements.txt' don't always match the name used to import them. We could call our to pip at the command line, but that doesn't seem ideal.
