### ISSUE TITLE
Need IS-04 test verifying referential integrity in Devices' senders and receivers list

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#198]
I just got assigned a bug in my code that the tests missed: There were senders listed in /x-nmos/node/v1.2/senders/ than there were not in the "senders" list in  .../devices/<device_id>. The should be a test to verify that each of the senders is listed in the list of senders in its device, and vice-versa.

I don't know how this fits in with the deprecation of the senders and receivers lists in the devices -- presumably not at all, or is this a "soft fail", or...?

**Comment by garethsb-sony** [comment]
The trouble with this for Registries is the chicken and egg problem, of the Device and Sender/Receiver resources being registered independently, so from the Registry's point of view there must always be a window when the registrations are out of sync, even if everything agrees once the system is in a steady state.

However, testing the Node API, I agree that this test may be worth adding, depending on how we view the deprecation. An `OPTIONAL` result at worst though?

**Comment by garethsb-sony** [comment]
More generally, it doesn't actually look like there's even a test case in `IS0401Test` that checks the referential integrity of the 'super-resource' ids, i.e. Device's `"node_id"`, Source's `"device_id"`, etc. That definitely needs adding.

**Comment by billt-hlit** [comment]
> An `OPTIONAL` result at worst though?

I think that `OPTIONAL` should only be valid if the list in the device record is the empty list. In my case, the senders list contained a subset of valid devices, which should provoke an outright `FAIL`.

**Comment by garethsb-sony** [comment]
That seems reasonable.

**Comment by billt-hlit** [comment]
Regarding Gareth's comment about super-resources: I just noticed that IS-04 requires that "resources must be registered in the correct order, such that a Receiver which references a device_id is registered after that corresponding Device (for example)." Does the test registry enforce this? If not, then the test I proposed may have to do something like compare the registration times of the resource and its parent, not just check for the parent's existence.

**Comment by garethsb-sony** [comment]
We test a Registry rejects resource registrations if the parent resources aren't already present (`IS0402Test.test_26`) but no, there doesn't appear to be any referential integrity checking in `IS0401Test` of a Node's POSTs to the mock Registries.
