### ISSUE TITLE
BCP-003-01: Browser/OpenSSL trouble with ECDHE and secp521r

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#206]
While testing `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` and `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`, I'm having trouble with the generated certificates.

This seems to be to do with the choice of `secp521r` (Standards For Efficient Cryptography Recommended 521-bit Elliptic Curve Domain Parameters over Fp) in the `generateCerts` script, here:

https://github.com/AMWA-TV/nmos-testing/blob/b2bee626475fe7a10c349153a13d790704090296/test_data/BCP00301/ca/generateCerts#L17

If I switch this to `secp256r1`, all my troubles go away (or at least, I'm onto the next ones 😉).

The reason that the 521-bit parameters seem to cause a problem are:

* Chrome seems to have actually _removed_ support for this variant
  * https://security.stackexchange.com/questions/100991/why-is-secp521r1-no-longer-supported-in-chrome-others
  * https://stackoverflow.com/questions/36928993/ecc-certificates-not-working-in-chrome
* Internet Explorer on the other hand seems not to support this by default (only 256-bit and 384-bit variants)
  * Using `gpedit.msc` to edit the *Computer Configuration > Administrative Templates > Network > SSL Configuration Settings* to explicitly include `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521` and `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P521` I have found it can be made to work however ([Manage Transport Layer Security](https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls))
* Finally, on the _server_ side, OpenSSL v1.0 (and v1.1?) seems to have trouble if the curve is not the same between ECDHE and ECDSA (e.g. [this issue](https://github.com/openssl/openssl/issues/2033)) - sounds like the negotiation was maybe unclear in the TLS v1.2 spec?

**Comment by andrewbonney** [comment]
@garethsb-sony can we close this one following #211?

**Comment by garethsb-sony** [comment]
Yep, thanks. Resolved by #211 (specifically 669399a72ec3b02daac9a0fbf86e39342819495f).

**Comment by garethsb-sony** [comment]
Just came across another reference for this issue:
* [Mozilla - Security/Server Side TLS - Recommended configurations - Modern compatibility](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) says "We recommend ECDSA certificates with P256 as other curves may not be supported everywhere."
