### ISSUE TITLE
Problems with reports for tests from command lines

### ISSUE THREAD

**Issue by Genri1441** [AMWA-TV/nmos-testing#208]
Hi AMWA team! 
I'm Alexander from Macnica company. I'm using your test suite for test NMOS stuff. It works very well. Thank you for it.
I found some problem with reports only. I'm trying to implement this test suite to Jenkins. It works well. 
I got only one issue. The report looks very strange. 
When I execute the test suite from cmd on Windows 10 or Linux Centos 7 - the result it the same for all environments. 
I'm using the following command while executing.
python nmos-test.py suite IS-04-01 --selection auto --host 192.168.59.250 --port 3000 --version v1.3 --output results41v1.3.xml

After executing, I get a report like this. 
![image](https://user-images.githubusercontent.com/45367554/56287934-525d2b80-6126-11e9-8fcd-c23579a4272b.png)
It just on one line for all tests. And Jenkins can't pars it.
 
I've changed it a little bit and it looks like that.
![image](https://user-images.githubusercontent.com/45367554/56288153-cdbedd00-6126-11e9-8a36-6598670bedd9.png)

Jenkins will get it like this.
![image](https://user-images.githubusercontent.com/45367554/56288212-f941c780-6126-11e9-96cc-94480a1c654b.png)
![image](https://user-images.githubusercontent.com/45367554/56288247-0e1e5b00-6127-11e9-87af-dc2a4254882a.png)
I can provide more details if you need. 

After editing the Jenkins detected this report as Google tests v1.6.

Will appreciate your support.
Waiting for your soonest reply.
Best regards.
Alexander.

**Comment by Genri1441** [comment]
Hi, AMWA team!
I've checked your test suite. Now it looks much better, but Jenkins can't understand these reports because of this. 

![image](https://user-images.githubusercontent.com/45367554/56359119-51410280-61e9-11e9-8c09-11e7e0949c85.png)

I've moved the "classname" to the end and now Jenkins and the xunit plugin can understand it.

![image](https://user-images.githubusercontent.com/45367554/56359255-b268d600-61e9-11e9-9407-6e0fdfe9a92d.png)

**Comment by andrewbonney** [comment]
Hi @Genri1441, could you share your XML output as a file? Have you also tried the plain JUnit plugin within Jenkins? I've tried the JUnit plugin with some test suite output and it doesn't seem to have a problem with it.

**Comment by Genri1441** [comment]
Hi @andrewbonney ! I'm using XUnit plugin :) I can try JUnit.  
This file works fine on Jenkins with XUnit.
https://docs.google.com/uc?export=download&id=1bQiiPWcvRU9MEQzY0YMfWFIPL9ot6S89

**Comment by andrewbonney** [comment]
Could you share a file that doesn't work too?

**Comment by Genri1441** [comment]
of course, here the link: https://drive.google.com/file/d/1o43oOwJ5UY7w8MrXhEQ5uXlPcJtZ6p1P/view?usp=sharing

**Comment by garethsb-sony** [comment]
Hmm, that's a bit confusing. In the first picture, it looks like you're saying the `<failure>` element is the problem. But in the second picture, it looks like you're saying that the fix is placing the `classname` attribute last on the `<testcase>` element.

Just reordering an attribute shouldn't make any difference to an XML processor. The fact that it does, and that the lack of whitespace / new-lines previously presented problems, makes me wonder if the Jenkins plugin you're using is trying to parse XML with a regex. 😒

**Comment by andrewbonney** [comment]
I'm having trouble accessing the second file, but the first one doesn't work for me with the JUnit plugin. It also doesn't appear to validate as XML due to the additional self-closing tags after the 'classname' attributes (see https://codebeautify.org/xmlvalidator for example).

**Comment by garethsb-sony** [comment]
Agreed, the first file that "works fine" isn't valid xml.

**Comment by garethsb-sony** [comment]
Looking at the [xunit plugin info](https://wiki.jenkins.io/plugins/servlet/mobile?contentId=38633556#content/view/38633556) I wonder why it is recognising the output as Google Test not Ant JUnit.

Required schema: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by Genri1441** [comment]
Hi guys! After some magic with Jenkins. Something like update these and update plugin. This XML files can be parsed from Jenkins. 
![image](https://user-images.githubusercontent.com/45367554/56497309-ab053d80-6505-11e9-8bab-564972dce50d.png)

Could you please push this changed to master? From master this didn't work, but from noninteractive-fix-208 branch works fine.

**Comment by garethsb-sony** [comment]
Hi @Genri1441 , @andrewbonney ,

I'm glad if PR #209 _does_ solve the issue...

It is a bit perplexing however that the Jenkins xUnit plugin documentation says the XML must validate against either the [Ant JUnit test report schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) or the [Maven Surefire test report schema](http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd), and as far as I can see the output from the [python-junit-xml module](https://github.com/kyrus/python-junit-xml) doesn't validate against either of those...

Shall we just apply the PR and move on anyway?

**Comment by andrewbonney** [comment]
I think that makes sense. I've merged the PR. We can deal with anything further in a new issue if necessary.
