### ISSUE TITLE
BCP-003-01: Intermediate CA common name needs to be different

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#219]
This has taken a *lot* of sleuthing by @simonlo-sony!

On most environments (e.g. Apache webserver, manually configured OpenSSL) one sets up the certificate chain to be served manually (and all is good with our NMOS Test CA!). However, on Windows, using Http.Sys and Schannel, the OS builds the chain automatically from the Windows trust store, starting from the server certificate bound to the address/port.

What we have found is that Windows servers were only sending the server cert, not the intermediate CA cert, and since the client only trusts the root CA cert, there was no chain of trust.

The problem seems to be that after considering the server cert, Schannel skips the intermediate CA cert because the root CA has the same common name (CN) of 'ca.testsuite.nmos.tv'.

(Schannel nevers sends the root CA cert, which makes sense from an efficiency point of view when in most circumstances the client either already has the root CA cert, or won't be prepared to start trusting an unknown root CA it gets sent.)

Guidance that using a different CN for the intermediate and root CA is a good idea also comes from https://jamielinux.com/docs/openssl-certificate-authority/create-the-intermediate-pair.html#create-the-intermediate-certificate which says:

"Use the intermediate key to create a certificate signing request (CSR). The details should generally match the root CA. The **Common Name**, however, must be different."

(Unfortunately there is no further explanation!)

Andrew, please would you mind updating the `generateCA` script and regenerating the certificates using an intermediate CN of e.g. 'ica.testsuite.nmos.tv'? (I'm not convinced an intermediate CA needs a SAN, but for simplicity that might as well be made the same too.)

Thanks!

**Comment by andrewbonney** [comment]
That sounds like it was fun...
