### ISSUE TITLE
Feature Request: Limit test to one host interface

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos-testing#229]
Hi,
I didn't ind anything about the "allowed" interface in the config.py, but is it possible to limit the test host interface?

I have four interface, but I would like the test to only run against one interface...

For example, my device is in subnet B available through interface B, but the test advertise it-self in the mDNS with subnet A.. therefore, my device cannot reach it, and I fail test...

**Comment by andrewbonney** [comment]
Hi. Could I just confirm which subnet has the default route associated with it? The test suite's behaviour is intended to be that it advertises using the interface which has the default route, but it ought to be possible to add a configuration option for this.

This is linked to but not quite the same as https://github.com/AMWA-TV/nmos-testing/issues/214 given that one covers browsing and this appears to be an advertisement issue.

**Comment by a1800bert** [comment]
This is not enough I think, on my setup as for example, my interface using the default gateway is to reach the company network (network, intranet,...) but my setup is on my secondary interface which as no gateway....

**Comment by andrewbonney** [comment]
Hopefully the change in https://github.com/AMWA-TV/nmos-testing/pull/231 will fix this. It should allow you to configure a preferred interface if the one which is chosen automatically is inappropriate.
