### ISSUE TITLE
Update IS-04/IS-05 tests to fully support v1.3 and v1.1 respectively

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#268]
This relates to https://github.com/AMWA-TV/nmos-testing/issues/152

**Comment by mjeras** [comment]
IS-04 test 20 on IS-07 senders gives this error:
```
Traceback (most recent call last):
  File "C:\Source\NMOS\nmos-testing\GenericTest.py", line 139, in execute_test
    self.result.append(method(test))
  File "C:\Source\NMOS\nmos-testing\IS0401Test.py", line 1042, in test_20
    if href.startswith("http") and not href.startswith(self.protocol + "://"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Probably due to the field not being there (allowed in v1.3). Probably there should be in if checking the existence of the field before running the check...

**Comment by andrewbonney** [comment]
Should now be resolved. Tests for 409 codes and WebSockets will be added separately.
