### ISSUE TITLE
Registry Server keeps closing the connection

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos-testing#271]
I'm stuck at test_02 which is "Node can discover network registration service via unicast DNS"

My device get the info from the DNS, start to POST its data, but I get a "tcp flag FIN/PSH/ACK" from the server... therefore, I'm closing the session (FIN flag)... But I can't figure out why, I'm receiving a FIN!

When I'm using SONY registry I get no issue.... 

I've attach wireshark traces of the sequence... You can see packet7 is the response from the registry... and send me the TCP flag (FIN)

[embox_to_registry_exchange.pcapng.zip](https://github.com/AMWA-TV/nmos-testing/files/3331233/embox_to_registry_exchange.pcapng.zip)

Any idea?

**Comment by garethsb-sony** [comment]
The server's behaviour is acceptable. It accepted your HTTP/1.1 POST request but responded with HTTP/1.0 (see #120) and closed the connection. When a server behaves like this you have to open another connection for the next request.

Sony `nmos-cpp-registry` is HTTP/1.1 so will typically keep the connection open, but even with HTTP/1.1 you have to be able to deal with this.

**Comment by a1800bert** [comment]
Thanks Gareth, I'll see into this, didn't know about the version 1.0 that was closing the connection after each request, will modify my stuff accordingly!

**Comment by garethsb-sony** [comment]
See also #270.
