### ISSUE TITLE
Health Request

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos-testing#272]
When executing the test_05 "Node maintains itself in the registry via periodic calls to the health resource" I get a warning "Heartbeat POST contained a payload body. More Information".

However, in the schema it has a payload:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Response to a request to update a resource's health",
  "title": "Heartbeat response",
  "required": [
    "health"
  ],
  "properties": {
    "health": {
      "description": "Timestamp indicating the time in seconds at which the server recorded the heartbeat",
      "type": "string",
      "pattern": "^[0-9]+$"
    }
  }
}

Which one is wrong? The test or the Schema?

Thanks

**Comment by garethsb-sony** [comment]
Neither 🙂 that's the response schema.

**Comment by a1800bert** [comment]
Nah you're right! My bad!!

Read the schema too fast!

Thanks for the reply.
