### ISSUE TITLE
IS-04/IS-05 tests are not consistent

### ISSUE THREAD

**Issue by mjeras** [AMWA-TV/nmos-testing#279]
I have noticed that my senders pass the IS-04/IS-05 tests if only those tests are run, but fail if IS-05 tests are run before them. The cause of the failure is a remaining receiver ID in the subscription. I would assume that some cleanup code needs to be added before the tests to ensure consistent behavior...

**Comment by andrewbonney** [comment]
To add some clarification after discussion. The issue seems to be that we may need an extra test to catch a specific failure which has been observed. This is around setting and removing a subscribed sender_id or receiver_id in an IS-05 interaction and checking that IS-04 is updated correctly.
