### ISSUE TITLE
BCP-003-01: Provide windows certificates

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-testing#280]
The windows HTTP support requires the cert and key to be combined into a pfx file to be installed and usable.

The generation script is only missing the following `openssl pkcs12 -export -out certificate.pfx -inkey privateKey.key -in certificate.crt -certfile more.crt`

This would be much friendly for those who have to support windows.

For those with the same issue, I'm currently using this [tool](https://www.sslshopper.com/ssl-converter.html) on the side to do the job.

**Comment by andrewbonney** [comment]
@prince-chrismc could you see if #281 sorts this out? I can't easily test this on my hosts.

**Comment by prince-chrismc** [comment]
I was able to generate ( with some difficulty ), install, and deploy all with the pfx files that were generated.

---

running the script on __Windows__ `./generateCerts PROCESSES-WIN10 workshop.nmos.tv` reports errors.
```
name is expected to be in the format /type0=value0/type1=value1/type2=... where characters may be escaped by \. This name is not in that format: 'C:/Program Files/Git/C=GB/ST=England/O=NMOS Testing Ltd/CN=PROCESSES-WIN10.workshop.nmos.tv'
problems making Certificate Request
```

I am not sure how _C:/Program Files/Git_ was added, but running the creation with the `-subj` and entering the information in manual worked.

**Comment by garethsb-sony** [comment]
Hi @prince-chrismc, that'll be this issue:
https://stackoverflow.com/a/31990313

I'm not sure whether we can adapt the solution so we can have one script that works on both Windows and *nix.

**Comment by prince-chrismc** [comment]
Ahhh, thank you very much for unearthing the mystery. I think the current pull request it very complete and addresses the issue
