### ISSUE TITLE
Trigger test run via REST call?

### ISSUE THREAD

**Issue by daniel-pebble** [AMWA-TV/nmos-testing#291]
Hi All, 

Is it possible to trigger a test run using REST call?

Thanks, 
Daniel

**Comment by garethsb-sony** [comment]
No. But you could script the non-interactive mode.

**Comment by daniel-pebble** [comment]
Thanks for confirming Gareth!  Will take a look at the non-interactive mode

**Comment by garethsb-sony** [comment]
I'm interested to brainstorm around whether having a test suite REST API that could be scripted, would be a way around the current impasse that we can't test NMOS clients.

**Comment by andrewbonney** [comment]
Resolved by #291. Future additions of course welcome.
