### ISSUE TITLE
IS04-01 test_21: sleep/wait resumes too soon

### ISSUE THREAD

**Issue by ZutroyBE** [AMWA-TV/nmos-testing#297]
test_21: "Node correctly interprets a 200 code from a registry upon initial registration"
FAIL -> Node did not attempt to DELETE itself having encountered a 200 code on initial registration

This test is failing on my setup because the test disables the registry as soon as it receives the first POST. The DELETE is properly sent but receives a 500.

I added some logs to investigate the failure:

>  * Running test_21
Tue Jul 23 12:00:27 2019 REGISTRY ENABLED ON PORT 5102
Tue Jul 23 12:00:27 2019 WAITING UP TO 5  SECONDS
10.129.110.210 - - [23/Jul/2019 12:00:28] "POST /x-nmos/registration/v1.2/health/nodes/11111111-2222-4444-9999-444444444444 HTTP/1.1" 404 -
Tue Jul 23 12:00:28 2019 RESUMING
Tue Jul 23 12:00:28 2019 REGISTRY DISABLE ON PORT 5102
10.129.110.210 - - [23/Jul/2019 12:00:28] "POST /x-nmos/registration/v1.2/resource HTTP/1.1" 200 -
10.129.110.210 - - [23/Jul/2019 12:00:28] "DELETE /x-nmos/registration/v1.2/resource/senders/52303352-abe7-4061-a7ca-acd6f5aa15a1 HTTP/1.1" 500 -

It happens here: IS0401Test.py at line 1105
        # Wait for n seconds after advertising the service for the first POST from a Node
        self.primary_registry.wait_for_registration(DNS_SD_ADVERT_TIMEOUT)

**Comment by andrewbonney** [comment]
Thanks for the report. That does look like an issue having had a scan of the code. I'll make a revision shortly.

**Comment by andrewbonney** [comment]
I'm hoping that https://github.com/AMWA-TV/nmos-testing/pull/298 will fix it, but I'll check on that a little later today.
