### ISSUE TITLE
Unicast DNS server returns unexpected domain

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-testing#300]
When running the test suite on a remote system configured with `DNS_SD_MODE = 'unicast'` I was unable to discover the services available having manually specified the remote's IP address as my DNS server. 

When I ran Wireshark I caught the following [pcap](https://github.com/AMWA-TV/nmos-testing/files/3428381/bad-dns-sd-response.zip) and I was able to reproduce the problem with `nslookup -q=PTR lb._dns-sd._udp` always obtained the response ` lb._dns-sd._udp.{{ domain }}      name = @.{{ domain }}` The `@` was appended with the domain instead of being replaced.

I am not sure why the @ is incorrectly _not_ being resolved by the zone record. but I had to manually changes the follow [line](https://github.com/AMWA-TV/nmos-testing/blob/e6ee5b0dcc3bdd1e8fcbd7503550bbe2098a3779/test_data/IS0401/dns_base.zone#L9)
to read `lb._dns-sd._udp	IN	PTR	{{ domain }}.` in order to be able to discover any services.

Has this issue been seen before? Perhaps it's a problem with Bonjour on Windows?

**Comment by andrewbonney** [comment]
Thanks for the report. I haven't seen this before, but will try and replicate it locally now.

**Comment by andrewbonney** [comment]
Yes, I can see the same issue. This looks like it was simply an assumption that dnslib could handle the same zone file format as BIND. Your suggested fix does the job: https://github.com/AMWA-TV/nmos-testing/pull/301

I'd guess that some implementations assume that their DNS search domain is sufficient information to peform DNS-SD browses against, whilst others will obtain a list by using the results of this query.

**Comment by garethsb-sony** [comment]
> I'd guess that some implementations assume that their DNS search domain is sufficient information to peform DNS-SD browses against, whilst others will obtain a list by using the results of this query.

Yes, I'm sure that's it.
