### ISSUE TITLE
IS-08 test 5 incorrectly handles 204 responses

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#339]
Due to an earlier change. The 'string' parameter no longer exists, so a 204 code with an empty body is attempted to be parsed as JSON.

https://github.com/AMWA-TV/nmos-testing/blob/master/is08/activation.py#L97

**Comment by jasperpeeters** [comment]
What happened with this issue? 
Just stumbled upon this as well, suspecting this issue is still alive?

At the end of `activation.delete()` at some point `return self._getJSON()` is called, which throws the `ValueError`..

**Comment by andrewbonney** [comment]
In theory I think this was fixed by https://github.com/AMWA-TV/nmos-testing/commit/228f2a21fca58351f4f68544d46f1ec3482eba9d (which I failed to reference at the time). As I don't have an implementation to test against however it's possible it's not fixed properly.

**Comment by jasperpeeters** [comment]
Ok, than it's still open. In:
```
    def _processResponseObject(self):
        self._checkForErrors()
        self._checkStatusCode()
        self._checkResponseSchema()
        return self._getJSON()
```
there is no check. 
I'll setup a PR with a check for 204 and return None in those cases.
