### ISSUE TITLE
IS-05-01 test activating Sender transport_params updates SDP file

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#342]
The `IS0501Test.test_23` checks that Sender transport parameters are changeable, but it doesn't check that they are reflected into the SDP at the `/transportfile` endpoint when activated.

We need that, unless I've missed it somewhere!

**Comment by andrewbonney** [comment]
If we are able to add a simple way to check SDP attributes, we should also check that media information matches between the SDP file and the IS-04 Source/Flow attributes.

**Comment by garethsb-sony** [comment]
Yes, absolutely! Thanks for pointing that out!!

Not sure whether to raise this as a separate issue but I discovered recently that SDPoker doesn't report any warning or error for the following file:

```
v=0
o=- 0 0 IN IP4 0.0.0.0
s=Empty Sdp file
c=IN IP4 0.0.0.0/127
t=0 0
```

**Comment by andrewbonney** [comment]
Remaining items:

- [ ] Add SDP media attribute checks to IS-05-02
- [ ] Add empty SDP check to SDPoker

**Comment by andrewbonney** [comment]
The final part of this should be resolved by https://github.com/Streampunk/sdpoker/pull/20

**Comment by andrewbonney** [comment]
Closing this as the remaining part is outside of our control.
