### ISSUE TITLE
Number of Interfaces does not need to match number of Transport Parameter

### ISSUE THREAD

**Issue by grmph555** [AMWA-TV/nmos-testing#355]
When a device sends a redundant stream originating on one interface, there are two transport parameter sets needed, but only one IS-04 interface binding.
See https://amwa-tv.github.io/nmos-device-connection-management/tags/v1.0.1/docs/4.1._Behaviour_-_RTP_Transport_Type.html#separate-destination-addresses
for that specific usecase.

This test:
https://github.com/AMWA-TV/nmos-testing/blob/228f2a21fca58351f4f68544d46f1ec3482eba9d/IS0502Test.py#L531

will fail in this case.

**Comment by andrewbonney** [comment]
I believe this is covered by https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.2.1/html-APIs/schemas/sender.json and https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.2.1/html-APIs/schemas/receiver_core.json

The idea is to maintain consistency between IS-04 and IS-05 by listing the same interface twice in the IS-04 `interface_bindings`: "Where the redundancy mechanism sends more than one copy of the stream via the same interface, that interface should be listed a corresponding number of times."

**Comment by grmph555** [comment]
understood
