### ISSUE TITLE
IS-04-02 test_21_1 Uncaught exception parsing link_header

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-testing#368]
IS-04-02 test_21_1 could throw an uncaught exception if the link_header is not as expected:

> Uncaught exception. Please report the  traceback from the terminal to  https://github.com/amwa-tv/nmos-testing/issues. 'NoneType' object has no  attribute 'group'

Example header which throws the exception: 
`<http://10.30.6.236:9999/x-nmos/query/v1.2/nodes?paging.since=0:0&paging.limit=100>;rel="next",<http://10.30.6.236:9999/x-nmos/query/v1.2/nodes?paging.until=1566984786&paging.limit=100>;rel="prev"`

_Note the missing whitespace between `;` and `rel=` which is expected in the regex: `'<(?P<url>.+)>; rel="(?P<rel>.+)"'`_

RE does partially not match but the result (`None`) is still accessed.

Furthermore, the regex used for the link_header seems to be slightly off, as the RFC defines the whitespace as optional: 

>    The ABNF for the field value is:
> 
>      Link       = #link-value
>      link-value = "<" URI-Reference ">" *( OWS ";" OWS link-param )
>      link-param = token BWS [ "=" BWS ( token / quoted-string ) ]

`OWS` -> _optional whitespace_
[Source](https://tools.ietf.org/html/rfc8288#section-3)

**Comment by garethsb-sony** [comment]
Closed by #369.
