### ISSUE TITLE
Document which test suites to run when testing JT-NM TR-1001-1

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#374]
Requested by @bgilmer77 

Should include the test suites themselves, and ideally the individual tests too (although it may be simpler to say which ones not to run in that case). Should also flag any major items from the TR which aren't covered by this tool.

**Comment by garethsb-sony** [comment]
Ideally, we'd provide a script to run. This may mean adding ability to `--selection` to specify a list of test cases (and maybe alternative `--no-selection` to remove test cases instead?).

**Comment by andrewbonney** [comment]
I suspect `--ignore` will help there.

**Comment by garethsb-sony** [comment]
Ha, I didn't even notice we had that!! :laughing:
