### ISSUE TITLE
IS05Utils.check_perform_immediate_activation fails at "if stagedParam == activeParam" comparision... 

### ISSUE THREAD

**Issue by maxwalter79** [AMWA-TV/nmos-testing#389]
...when "stagedParam" equals to "auto" 

In my case  websocket IS-07 sender is checked by test suite "IS-05-05, test_25" and fails

Here are the senders  constraints where the "auto" parameter ist taken from for the test

```json
[
    {
        "connection_authorization": {
            "enum": [
                false
            ]
        },
        "connection_uri": {
            "enum": [
                "auto",
                "ws://192.168.178.30:4491/x-nmos/events/v1.0/device_id/2840863c-f15d-43a7-969b-59b65f3716f6"
            ]
        },
        "ext_is_07_rest_api_url": {
            "enum": [
                "auto",
                "http://192.168.178.30:4490/x-nmos/events/v1.0/sources/e1126855-658f-47b7-b380-b2576faf347c/"
            ]
        },
        "ext_is_07_source_id": {
            "enum": [
                "auto",
                "e1126855-658f-47b7-b380-b2576faf347c"
            ]
        }
    }
]
```

this behavior  affects also tests 16, 27, 29

**Comment by garethsb-sony** [comment]
Two issues here:

* Firstly, yes, if the `stagedParam` is `"auto"`, then the test actually needs to check that `activeParam` is **not** `"auto"`.
* Secondly, your implementation should not include `"auto"` in the `"enum"`, and we should have a test that WARNs if it does. See https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/2.2.%20APIs%20-%20Server%20Side%20Implementation.md#use-of-auto.

**Comment by maxwalter79** [comment]
though _https://amwa-tv.github.io/nmos-device-connection-management/tags/v1.1/html-APIs/schemas/sender_transport_params_websocket.json_ allowes "auto" values

How than should one node express his inability to accept an "auto" value patch?

**Comment by garethsb-sony** [comment]
Whether a property supports `"auto"` is defined by the spec for that property.
A Node MUST support `"auto"` if the spec says it is supported.

For `"connection_uri"`, the spec (and therefore the schema you linked) says `"auto"` is supported.
