### ISSUE TITLE
IS-07: exception are not caught in case of wrong number format

### ISSUE THREAD

**Issue by maweit** [AMWA-TV/nmos-testing#423]
If the number format is e.g. (2.0, 1) formats.Format throws a TypeError which is not caught in test 04 and 06. 
If the number format is e.g. (2, 0) formats.Format throws a ZeroDivisionError which is also not caught in 04 and 06. 
The latter is reported when checked against a schema but i think the reason entry should not show an uncaught exception.

So i propose to add some lines like: 
```
except TypeError as e:
           return test.FAIL("Source {} JSON data has wrong number type: {}".format(source_id, e))
except ZeroDivisionError as e:
           return test.FAIL("Source {} JSON zero data not allowed: {}".format(source_id, e))
```

**Comment by garethsb-sony** [comment]
Thanks, Martin!

Absolutely agree about the `ZeroDivisionError`.
Please can you give an example of JSON that causes the `TypeError`?

**Comment by maweit** [comment]
One example is: 
```
"payload": {
    "scale": 10,
    "value": 293.35
}
```
It throws:
wrong number type: both arguments should be Rational instances

**Comment by garethsb-sony** [comment]
OK, well I think that's a flaw in the test, and that payload should be permitted. Using the python `fractions` module seemed like a good fit, but maybe not... Hmmm, what about using `fractions.Fraction(payload["value"]) / fractions.Fraction(scale)` instead of `fractions.Fraction(payload["value"], scale)`?

**Comment by maweit** [comment]
`fractions.Fraction(payload["value"]) / fractions.Fraction(scale)` did not solve it. 
Using `fractions.Fraction(fractions.Fraction(payload["value"]), fractions.Fraction(scale))` does not throw the exception but gives the warning: `payload is not an integer multiple of the step`
I'm currently not sure if this format is allowed?

**Comment by garethsb-sony** [comment]
What is the `step` out of interest?
I think this format is not prohibited in the schema or discussed in the docs, though I agree I'm not sure whether support for it was intended...

**Comment by maweit** [comment]
Step is set to:
```
"step": {
    "scale": 10,
    "value": 1
}
```

**Comment by garethsb-sony** [comment]
Well then, that warning is correct, right?

**Comment by maweit** [comment]
Yes - sorry for the confusion. Just the line you proposed still gives the exception and i mentioned the warning for completeness .....

**Comment by garethsb-sony** [comment]
Based on your fix, does the slightly simpler `fractions.Fraction(fractions.Fraction(payload["value"]), scale)` work?

**Comment by maweit** [comment]
Yep! looks good.

**Comment by garethsb-sony** [comment]
OK, great, would you like to make a PR that includes the `get_number` fix and the `except ZeroDivsionError` lines?

**Comment by maweit** [comment]
Yes, will ...
