### ISSUE TITLE
IS-07: test_06_03 - boolean test passes if value is string 

### ISSUE THREAD

**Issue by maweit** [AMWA-TV/nmos-testing#435]
test_06_03 checks for a boolean source. If the payload value is set to e.g. a string "test" the test should fail.

**Comment by garethsb-sony** [comment]
Yes, it says it relies on the schema validation to check that... but that hasn't in fact been performed on every source.

**Comment by andrewbonney** [comment]
I've looked at adding this to the core 'auto' tests, but for cases such as registry testing where the individual resources are (mostly) already tested by a call to the parent path it increases the execution time significantly.

I could add a flag to perform complete schema validation in the auto tests for specific test suites, but this may be confusing for a user if different tests suites behave in different ways. For this reason I'd suggest it might be best to add an explicit test for schema validation of sub-resources to the IS-07 test suite instead.

**Comment by garethsb-sony** [comment]
Resolved by #524.
