### ISSUE TITLE
IS-08 Audio Channel Mapping - Index out of range

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-testing#445]
There are in total 4 occurrences where the outputs are retrieved and immediately accessed.
For example: 
```python
testRouteAction = outputList[0].findAcceptableTestRoute()
```
Line 75

This happens in `test_02`, `test_05`, `test_06` and in `    def check_delayed_activation(self, activationTime, activationType)`

Would it be sufficient to return a test.NA in these cases?

**Comment by andrewbonney** [comment]
I'd suggest using 'UNCLEAR', similar to how the IS-05 tests do here: https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/suites/IS0501Test.py#L118
