### ISSUE TITLE
Sender was registered before its referenced 'flow_id' 'None' 

### ISSUE THREAD

**Issue by wsneijers** [AMWA-TV/nmos-testing#479]
Running the test tool (at the time of writing commit 3dceff520ae0181c10dff9d02b90674d4739370f) I get the following warning:

![image](https://user-images.githubusercontent.com/10929317/73540713-f18ead80-4430-11ea-9ba4-3553cc132fbd.png)

The sender in question is defined in NMOS as follows:

![image](https://user-images.githubusercontent.com/10929317/73540842-3ca8c080-4431-11ea-89f7-57b49a3f5c49.png)

If I look at the schema it is allowed to have a sender with the `flow_id` set to `null` (https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/APIs/schemas/sender.json):

![image](https://user-images.githubusercontent.com/10929317/73540951-7ed20200-4431-11ea-9260-59d58a230a02.png)

However the test flags this as a warning. In my opinion this is not correct, however I would like to get some input.

**Comment by wsneijers** [comment]
Confirmed. This does solve the bug.

**Comment by garethsb-sony** [comment]
Thanks!
