### ISSUE TITLE
test_data SDP files are missing a PTP Domain

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-testing#482]
https://github.com/AMWA-TV/nmos-testing/blob/0c7213774a723cbf0dcf2df0f98fe25cc1297a39/test_data/IS0502/video.sdp#L8

based on https://github.com/AMWA-TV/sdpoker/pull/5

**Comment by garethsb-sony** [comment]
Good spot.

**Comment by garethsb-sony** [comment]
Also the ones in the IS-05 spec...

https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/examples/receiver-patch-transportfile.json

https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/examples/receiver-stage-scheduled-transportfile.json
