### ISSUE TITLE
IS-08-01: test_15, uncaught exception: 'list' object has no attribute 'id'

### ISSUE THREAD

**Issue by saisani** [AMWA-TV/nmos-testing#483]
test_15 produces an exception due to `output` variable being a list instead of being just an output object. 
```
def test_15(self):
...
 chosenInput = constrainedInputs[0]
        output = chosenInput.getRoutableOutputs()
        action = Action(
            chosenInput.id,
            output.id
        )
...
```
This can be fixed by accessing the first element of `output` in the `action` construction so that `output.id` becomes `output[0].id`.

**Comment by andrewbonney** [comment]
Thanks for the report. I've put that fix into a pull request.
