### ISSUE TITLE
IS-05 test_25 (Immediate activation of a sender) speed

### ISSUE THREAD

**Issue by wsneijers** [AMWA-TV/nmos-testing#484]
First of all thanks to everyone adding tests to this testing tool over the past weeks! It really has become a valuable tool for NMOS testing!

We are currently running through the test suites for the upcoming JT-NM certification. One test is causing us quite a lot of headaches. That is test_25 of the IS05_01 suite (Immediate activation of a sender). Mainly the time between sending the activation and checking the SDP files:

nmos-testing IS0501Test.py:
``` python
for sender in self.is05_utils.sampled_list(self.senders):
    # Sending activation
    valid, response = self.is05_utils.check_activation("sender", sender,
                                                        self.is05_utils.check_perform_immediate_activation,
                                                        self.transport_types[sender],
                                                        True)
    
    if valid:
        # SDP validation.
        if self.transport_types[sender] == "urn:x-nmos:transport:rtp":
            valid2, response2 = self.is05_utils.check_sdp_matches_params(sender)
            if not valid2:
                return test.FAIL("SDP file for Sender {} does not match the transport_params: {}"
                                    .format(sender, response2))
    else:
        return test.FAIL(response)
```
The testing tool immediately tries to validate the SDP file after the activation PATCH request. However with our stack (using Sony nmos-cpp as a separate daemon to a main application) there is some delay between the start of processing of the immediate activation and the update of the sender resource. 

Changing the code a little (by adding a sleep, I know very dirty) I can get the test to pass:

nmos-testing IS0501Test.py:
``` python
for sender in self.is05_utils.sampled_list(self.senders):
    # Sending activation
    valid, response = self.is05_utils.check_activation("sender", sender,
                                                        self.is05_utils.check_perform_immediate_activation,
                                                        self.transport_types[sender],
                                                        True)
    
    if valid:

        # Add a sleep to allow the SDP file to propagate to the resource.
        time.sleep(0.6)

        # SDP validation.
        if self.transport_types[sender] == "urn:x-nmos:transport:rtp":
            valid2, response2 = self.is05_utils.check_sdp_matches_params(sender)
            if not valid2:
                return test.FAIL("SDP file for Sender {} does not match the transport_params: {}"
                                    .format(sender, response2))
    else:
        return test.FAIL(response)
```

My question here: Is this realistic scenario that can happen? Because the IS-05 spec only says that, with an immediate activation, you need to immediatly process it. It does not specify (as far as I know) a maximum time for this change to propagate.

Thanks!

**Comment by garethsb-sony** [comment]
Wesley, I think the point of the immediate activation mode is that it guarantees the operation to have happened by the time the HTTP response has been received. Otherwise it's very similar to a scheduled-relative activation with an offset of `0:0` isn't it?

**Comment by wsneijers** [comment]
Thanks for the explanation Gareth! I didn't understand the difference clearly, but do now.
