### ISSUE TITLE
JT-NM NMOS

### ISSUE THREAD

**Issue by Mikew-Telestream** [AMWA-TV/nmos-testing#502]
When trying to install the requirements.txt file get the following error.

MAC-BEAV-Mike:nmos-testing mikew-mac$ pip3 install -r requirements.txt
Requirement already satisfied: flask>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: wtforms in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.2.1)
Requirement already satisfied: jsonschema in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: zeroconf-monkey in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.1.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (2.23.0)
Collecting netifaces
  Using cached netifaces-0.10.9.tar.gz (28 kB)
Collecting gitpython
  Using cached GitPython-3.0.8-py3-none-any.whl (450 kB)
Collecting ramlfications
  Using cached ramlfications-0.1.9-py2.py3-none-any.whl (49 kB)
Collecting websocket-client>=0.54.0
  Using cached websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting jsonref
  Using cached jsonref-0.2-py3-none-any.whl (9.3 kB)
Collecting dnslib
  Using cached dnslib-0.9.12-py3-none-any.whl (53 kB)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (2.11.1)
Collecting junit-xml
  Using cached junit-xml-1.8.tar.gz (10.0 kB)
Collecting rfc3987
  Using cached rfc3987-1.3.8-py2.py3-none-any.whl (13 kB)
Collecting pyopenssl
  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Requirement already satisfied: Werkzeug>=0.15 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: click>=5.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jsonschema->-r requirements.txt (line 3)) (41.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jsonschema->-r requirements.txt (line 3)) (0.15.7)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jsonschema->-r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jsonschema->-r requirements.txt (line 3)) (19.3.0)
Requirement already satisfied: zeroconf>=0.17.7 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from zeroconf-monkey->-r requirements.txt (line 4)) (0.24.4)
Requirement already satisfied: chardet<4,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests->-r requirements.txt (line 5)) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests->-r requirements.txt (line 5)) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests->-r requirements.txt (line 5)) (2.9)
Collecting gitdb2>=3
  Using cached gitdb2-3.0.2-py2.py3-none-any.whl (63 kB)
Collecting markdown2
  Using cached markdown2-2.3.8-py2.py3-none-any.whl (33 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.tar.gz (268 kB)
Collecting xmltodict
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting termcolor
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jinja2->-r requirements.txt (line 12)) (1.1.1)
Collecting cryptography>=2.8
  Using cached cryptography-2.8-cp34-abi3-macosx_10_6_intel.whl (1.6 MB)
Requirement already satisfied: ifaddr in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from zeroconf>=0.17.7->zeroconf-monkey->-r requirements.txt (line 4)) (0.1.6)
Collecting smmap2>=2.0.0
  Using cached smmap2-2.0.5-py2.py3-none-any.whl (24 kB)
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.14.0-cp38-cp38-macosx_10_9_x86_64.whl (175 kB)
Collecting pycparser
  Using cached pycparser-2.19.tar.gz (158 kB)
Installing collected packages: netifaces, smmap2, gitdb2, gitpython, markdown2, pyyaml, jsonref, xmltodict, termcolor, ramlfications, websocket-client, dnslib, junit-xml, rfc3987, pycparser, cffi, cryptography, pyopenssl
    Running setup.py install for netifaces ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-install-q5nukgvu/netifaces/setup.py'"'"'; __file__='"'"'/private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-install-q5nukgvu/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-record-ow9futex/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/netifaces
         cwd: /private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-install-q5nukgvu/netifaces/
    Complete output (16 lines):
    running install
    running build
    running build_ext
    checking for getifaddrs...not found.
    checking for getnameinfo...not found.
    checking for socket IOCTLs...not found.
    checking for optional header files...none found.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...none!
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...no.
    building 'netifaces' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DNETIFACES_VERSION=0.10.9 -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c netifaces.c -o build/temp.macosx-10.9-x86_64-3.8/netifaces.o
    xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-install-q5nukgvu/netifaces/setup.py'"'"'; __file__='"'"'/private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-install-q5nukgvu/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/97/0_5cjlhx61g383x8n4sq58t40000gn/T/pip-record-ow9futex/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/netifaces Check the logs for full command output.

I was able to get the docket container to work and load the localhost page but unclear on how to setup the folder I am using on my mac for where the config.py is located.

**Comment by garethsb-sony** [comment]
I'm not a regular Mac user, but I think the **xcrun : error** is the crux of the problem. Google search suggests problems with install of the Xcode command line tools. There are some suggestions to try here: https://github.com/Homebrew/legacy-homebrew/issues/23500
Sorry I can't help more right now.

**Comment by andrewbonney** [comment]
Hi @Mikew-Telestream, did you manage to resolve this?

**Comment by Mikew-Telestream** [comment]
No not directly, my PC will not run in the command line but would run in a Docker container, but does not appear to pull the config file correctly.

So found another pc which did run the command line correctly however when I set to True it go through the process but appears never to report the result back to the browser as shown below but browser just shows executing and never reports back the data.

[A screenshot of a cell phone  Description automatically generated]
[A screenshot of a cell phone  Description automatically generated]

**Comment by andrewbonney** [comment]
Following up via e-mail
