### ISSUE TITLE
IS-09 System API Discovery

### ISSUE THREAD

**Issue by TobiasThierolf** [AMWA-TV/nmos-testing#506]
Hello everybody,
I am fairly new to nmos, so maybe some of my assumptions are incorrect or I am missing some important information here.

I've added an implementation that reads the ptp settings from the System API. It runs fine with the nmos-cpp-registry application that offers a System API interface. I've tried to validate it with the IS-09 System API Discovery test, but it fails and I don't really understand why. 

The first thing to mention here is that the python script of the test application throws an exception, maybe this is causing the trouble here but I am not sure what the reason for this exception is. I've installed all the packets listed in the requirements.txt and my python version is 3.5.3, so I don't see any setup related issue. 

This is how the exception looks:
```
Traceback (most recent call last):
  File "/home/tth/test/nmos-testing-master/nmostesting/NMOSTesting.py", line 373, in index_page
    results = run_tests(test, endpoints, test_selection)
  File "/home/tth/test/nmos-testing-master/nmostesting/NMOSTesting.py", line 430, in run_tests
    if endpoints[index]["host"] is not None and endpoints[index]["port"] is not None:
nmostesting.GenericTest.NMOSInitException: All IP/Hostname and Port fields must be completed
```

But even with the exception the test is running.

If I check the System APIs offered by the test application, I see three System APIs.
Only one of them has valid parameters and this one is selected by the application.
A request to the System API is send and the response is: ["global/"]. So far so good, then another request is send to the "global/" node and the response is a HTTP 404 error code:

```
192.168.10.209 - - [04/Mar/2020 10:51:48] "GET /x-nmos/system/v1.0/global/ HTTP/1.1" 404 - "http://192.168.10.209:5302" "cpprestsdk/2.10.14"
```

This happens a couple of times, since I am polling the Sytem APIs periodically. Then the test stops and reports failure for test_01 "Node can discover System API via multicast DNS". The System API discovery happened and a request to the SystemAPI was send. Is there something missing or why does the test not pass?

**Comment by garethsb-sony** [comment]
Hi Tobias.

I don't see that exception running the Testing Tool in interactive mode via the web UI or when using the non-interactive mode with:

```
py nmos-test.py suite IS-09-02 --host 10.0.0.1 null --port 0 0 --version null v1.0 --output results.xml
```

Are you using the **/api** endpoint? You'll need to provide two entries for the host, port and version arrays similar to the above in your request.

**Comment by garethsb-sony** [comment]
> So far so good, then another request is send to the "global/" node and the response is a HTTP 404 error code

As for this, that would be due to the lack of `strict_slashes=False here:
https://github.com/AMWA-TV/nmos-testing/blob/0cfdfb67962ead0edd46d7de63df0908b181d007/nmostesting/mocks/System.py#L57

@andrewbonney I think that's an oversight?

**Comment by TobiasThierolf** [comment]
Hi Gareth,
I am using the web UI. The only thing I can configure from that perspective is the IP/Hostname for the Node API. 
I will remove the trailing slash in the request and retry it.

**Comment by garethsb-sony** [comment]
Please would you try clearing your cookies and let me know if that solves the exception issue?

**Comment by TobiasThierolf** [comment]
Ok, silly me,
removing the trailing slash makes the test pass and also the exception is gone.

Thank you very much for your support!

**Comment by garethsb-sony** [comment]
@TobiasThierolf Not silly, you identified a flaw in the System mock in the testing tool, thanks! Changing your implementation to make the request without the trailing slash is still RECOMMENDED though, based on the guidance at [URLs: Approach to Trailing Slashes](https://amwa-tv.github.io/nmos-system/branches/v1.0-dev/docs/2.0._APIs.html#urls-approach-to-trailing-slashes).
