### ISSUE TITLE
IS-08 test_01 and test_02 throw an exception

### ISSUE THREAD

**Issue by maxwalter79** [AMWA-TV/nmos-testing#532]
Hi guys!

I'm starting to look in our IS-08 implementation again and run in this issue with test-suite.

Here is the stack trace of both tests which fail due to an exception:

```
 * Running test_01
 * Running test_02
Traceback (most recent call last):
  File "/home/ip/github/nmos-testing/nmostesting/GenericTest.py", line 153, in execute_test
    self.result.append(method(test))
  File "/home/ip/github/nmos-testing/nmostesting/suites/IS0802Test.py", line 54, in test_01
    for device in devicesWithAdvertisements:
TypeError: 'TestResult' object is not iterable
Traceback (most recent call last):
  File "/home/ip/github/nmos-testing/nmostesting/GenericTest.py", line 153, in execute_test
    self.result.append(method(test))
  File "/home/ip/github/nmos-testing/nmostesting/suites/IS0802Test.py", line 82, in test_02
    if len(self.find_device_advertisement()) > 0:
TypeError: object of type 'TestResult' has no len()
```

![image](https://user-images.githubusercontent.com/24458376/81534106-bffa7c00-9367-11ea-9bfe-fe849652c038.png)

This is how my IS-08 settings look like (no device selector specified)

![image](https://user-images.githubusercontent.com/24458376/81534443-5333b180-9368-11ea-851c-a78554953963.png)

I'm running the test-suite locally with "ENABLE_DNS_SD = False" in Config.py

If you need more information just contact me. Thank you in advance!

**Comment by garethsb-sony** [comment]
I think it means your implementation didn't respond as expected, but the test code on the failure path just looked wrong. I've made a PR, please would you try it, Max?

**Comment by maxwalter79** [comment]
Looks good now Gareth, thank you very much!

![image](https://user-images.githubusercontent.com/24458376/81562280-d8cd5680-9394-11ea-95a9-69644cfb7e91.png)
