### ISSUE TITLE
IS-04 Node API and IS-04 Registry APIs: No error code and error information for "Missing Authorization Header"

### ISSUE THREAD

**Issue by simonlo-sony** [AMWA-TV/nmos-testing#565]
Authorization test against "Missing Authorization Header" should test for NO error code and error information.

How about the error response body, should it also be NOT including the error code and other error information?

**Comment by prince-chrismc** [comment]
#561

**Comment by andrewbonney** [comment]
@simonlo-sony is this one resolved now?

**Comment by simonlo-sony** [comment]
> @simonlo-sony is this one resolved now?

yes resolved
