### ISSUE TITLE
No ARM nmos-testing container - Breaks "easy-nmos" solution on ARM

### ISSUE THREAD

**Issue by rhastie** [AMWA-TV/nmos-testing#579]
Currently we have a mismatch with "easy-nmos" when it is installed on ARM CPU architectures. The nmos-cpp containers support multi-arch and are built for AMD64 and ARM64/32. The nmos-testing container is only built for AMD64... This means easy-nmos fails to run the nmos-testing container on ARM CPU installs.

Can we move the nmos-testing container from a Docker Hub build process to a GitHub Actions build process? This will give you the ability to build the container for multi-architecture under the Docker "buildx" process. You can then push the container to Docker Hub using a multi-arch manifest which resolves the above issues.

I'm happy to work with someone on this... Ultimately it will give AMWA a better solution as the nmos-testing container will be fully supported on ARM CPU architectures.

**Comment by peterbrightwell** [comment]
@rhastie https://github.com/AMWA-TV/nmos-testing/pull/602 moves the container build and upload to GitHub Actions (runs scripts in .deploy).
