### ISSUE TITLE
IS-04-02 test_01/test_02 and IS-04-03 test_01 broken by python-zeroconf 0.28.6

### ISSUE THREAD

**Issue by rhastie** [AMWA-TV/nmos-testing#583]
Running the latest release of the test suite is causing uncaught errors on test_01/test_02 in the IS-04-02 suite. There appears to be new additions for "Authorisation" testing - Am I doing something wrong now in running the tests?

Please see below for relevant outputs:

From stderr output:
> nmos-testing     | Traceback (most recent call last):
nmos-testing     |   File "/home/nmos-testing/nmostesting/GenericTest.py", line 145, in execute_test
nmos-testing     |     self.result.append(method(test))
nmos-testing     |   File "/home/nmos-testing/nmostesting/suites/IS0402Test.py", line 128, in test_01
nmos-testing     |     return self.do_dns_sd_advertisement_check(test, api, service_type)
nmos-testing     |   File "/home/nmos-testing/nmostesting/suites/IS0402Test.py", line 72, in do_dns_sd_advertisement_check
nmos-testing     |     ServiceBrowser(self.zc, service_type, self.zc_listener)
nmos-testing     |   File "/usr/local/lib/python3.6/dist-packages/zeroconf/__init__.py", line 1566, in __init__
nmos-testing     |     if not check_type_.endswith(service_type_name(check_type_, strict=False)):
nmos-testing     | TypeError: service_type_name() got an unexpected keyword argument 'strict'
nmos-testing     | Traceback (most recent call last):
nmos-testing     |   File "/home/nmos-testing/nmostesting/GenericTest.py", line 145, in execute_test
nmos-testing     |     self.result.append(method(test))
nmos-testing     |   File "/home/nmos-testing/nmostesting/suites/IS0402Test.py", line 135, in test_02
nmos-testing     |     return self.do_dns_sd_advertisement_check(test, api, "_nmos-query._tcp.local.")
nmos-testing     |   File "/home/nmos-testing/nmostesting/suites/IS0402Test.py", line 72, in do_dns_sd_advertisement_check
nmos-testing     |     ServiceBrowser(self.zc, service_type, self.zc_listener)
nmos-testing     |   File "/usr/local/lib/python3.6/dist-packages/zeroconf/__init__.py", line 1566, in __init__
nmos-testing     |     if not check_type_.endswith(service_type_name(check_type_, strict=False)):
nmos-testing     | TypeError: service_type_name() got an unexpected keyword argument 'strict'
nmos-testing     | 192.168.1.34 - - [20/Oct/2020 08:40:45] "POST / HTTP/1.1" 200 - "http://nmos-testing.local:5000" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

From testing tool output see attached image file "IS-04-02_output.jpg"
![IS-04-02_output](https://user-images.githubusercontent.com/8142770/96563422-d7944400-12b9-11eb-8162-1ffa53d0600a.jpg)

JSON output added as file "IS-04-02_1603183627.json"
[IS-04-02_1603183627.json.log](https://github.com/AMWA-TV/nmos-testing/files/5407516/IS-04-02_1603183627.json.log)

**Comment by garethsb-sony** [comment]
Breaking change in python-zeroconf API, that breaks our zeroconf monkey patch, which I haven't got around to fixing yet, partly because I hope they'll respond to https://github.com/jstasiak/python-zeroconf/issues/311 which would make zeroconf-monkey redundant.

**Comment by andrewbonney** [comment]
@rhastie I've just patched 'zeroconf-monkey'. If you're doing a fresh install of the testing tool I'd hope this will now resolve things. If you already have zeroconf-monkey and zeroconf installed you'll need to remove them first and then reinstall.

**Comment by rhastie** [comment]
@andrewbonney Did the container image get rebuilt? Or is it an overnight thing? Or is it still rebuilding it?

I've re-tested with a fresh container install and I'm still showing errors. Importantly, Docker Hub is reporting that the image is over a day old so I suspect I still have the bug etc.

**Comment by andrewbonney** [comment]
Ah sorry, that only gets rebuilt explicitly when this repo changes. The modification was made to an external dependency.

I've just triggered a manual rebuild which has generated a new image.

**Comment by rhastie** [comment]
@andrewbonney - Thanks! Suite IS-04-02 test_01/test_02 are now passing with no errors... I didn't test IS-04-03

**Comment by garethsb-sony** [comment]
@andrewbonney I'm not against pinning python-zeroconf given how many times they've broken their API, but do we want this issue closed, or leave open to track the possiblity of getting rid of the zerconf-monkey patch completely?

**Comment by andrewbonney** [comment]
I'm happy for this one to be re-opened to track that, or have another issue added specifically for it.
