### ISSUE TITLE
IS-04 Node, test_20, could be failed due to case sensitive hostname comparison

### ISSUE THREAD

**Issue by simonlo-sony** [AMWA-TV/nmos-testing#595]
If upper case is used in the hostname entry, test_20 failed.  

Suggest to perform non case sensitive hostname comparsion in test.

**Comment by garethsb-sony** [comment]
All you could ever want to know about case-insensitive comparison in Python: https://stackoverflow.com/questions/319426/how-do-i-do-a-case-insensitive-string-comparison

All you could ever want to know about case-insensitive comparison of DNS names: https://tools.ietf.org/html/rfc4343

**Comment by garethsb-sony** [comment]
On that basis, looks like only the one comparison `endpoint["host"] == api["hostname"]` might need tweaking to solve this.

FWIW, there are a bunch of places where we check URL schemes case sensitively, but writing e.g. HTTP://... in uppercase ought to be punished no matter what https://tools.ietf.org/html/rfc3986#section-3.1 says, so there's no need to change all of those!
