### ISSUE TITLE
IS-04 Node API - Error: No branch matching the expected patterns was found in the Git repository

### ISSUE THREAD

**Issue by athanipranoti** [AMWA-TV/nmos-testing#609]
I am running into this error "Error: No branch matching the expected patterns was found in the Git repository" while trying to run IS-04 Node API test suite.

**Comment by garethsb** [comment]
Not sure, but you could try deleting the **cache** directory and trying again. Are there any other errors in the console log?

**Comment by athanipranoti** [comment]
Tried "docker builder prune" but it did not help.

Error from logs - 
Traceback (most recent call last):
  File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 386, in index_page
    results = run_tests(test, endpoints, test_selection)
  File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 511, in run_tests
    test_obj = test_def["class"](apis, REGISTRIES, NODE, DNS_SERVER)
  File "/home/nmos-testing/nmostesting/suites/IS0401Test.py", line 44, in __init__
    GenericTest.__init__(self, apis)
  File "/home/nmos-testing/nmostesting/GenericTest.py", line 104, in __init__
    raise Exception("No branch matching the expected patterns was found in the Git repository")
Exception: No branch matching the expected patterns was found in the Git repository

**Comment by garethsb** [comment]
I didn't realise you were using the docker container. Does it have Internet access to fetch the specifications? At the top of the log you should see messages like:

Pulling latest files for repository ...

**Comment by athanipranoti** [comment]
Okay. I pulled the latest image and that seems to have resolved the error. Thank you for your quick response.
