### ISSUE TITLE
[IS-05] connection sender staged appears to use the wrong schema

### ISSUE THREAD

**Issue by kierank** [AMWA-TV/nmos-testing#626]
I expect the testsuite to use this schema: https://specs.amwa.tv/is-05/releases/v1.1.0/APIs/schemas/resolved/sender-stage-schema.html

But I get this error from a different schema:

![image](https://user-images.githubusercontent.com/143888/143332703-bd2b1bb9-5424-4635-9141-631dbb8cae53.png)

**Comment by garethsb** [comment]
Ah, now I see the problem. The schema we've been looking at is the one for the `PATCH` request to _/staged_. The testing tool is checking the response, which is covered by this schema: https://specs.amwa.tv/is-05/releases/v1.1.0/APIs/schemas/resolved/sender-response-schema.html.

**Comment by garethsb** [comment]
By way of explanation, in a `PATCH` request the client is requesting an activation and may for example specify it is scheduled immediately or relative to the current time. In the response to this "stage" request, and in subsequent responses to `GET` requests, the activation time indicates the time at which the activation will or did actually happen.
