### ISSUE TITLE
Uncaught Exception found in test_15 under the test suite IS-05 Interaction with IS-04

### ISSUE THREAD

**Issue by pimiller** [AMWA-TV/nmos-testing#638]
I came across this exception:

                <testcase classname="IS-05-02" name="test_15" time="0.000041" timestamp="19:13:29.831">
                        <failure message="Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. FAIL() takes from 2 to 3 positional arguments but 4 were given" type="Fail"/>
                </testcase>

Seems to be coming from this line (from nmostesting/suites/IS0502Test.py):

    784                                     if len(flow["components"]) != 3:
    785                                         return test.FAIL("Video Flow {} components do not match those found in SDP for "
    786                                                          "Sender {}", flow["id"], resource["id"])

**Comment by garethsb** [comment]
Thanks!
