### ISSUE TITLE
IS-05 Controller: multicast_ip and source_ip not set on mock receivers

### ISSUE THREAD

**Issue by KonradDuda** [AMWA-TV/nmos-testing#647]
For test_02, when a `PATCH` is performed by the NCuT that sets the mock receiver's `sender_id` to the `id` of the sender and the receiver's `transport_file data` to the sender's SDP, both the `PATCH` response and a subsequent `GET` of the receiver's `/active` endpoint have the `multicast_ip` and `source_ip` in the `transport_params` set to `null`. I believe they should be set to the `multicast_ip` and `source_ip` set in the `transport_file data`.

For test_04, after the connection is made by the testing tool, the response to a subsequent `GET` of the receiver's `/active` endpoint has the `multicast_ip` and `source_ip` in the `transport_params` set to `null` instead of the values from the sender that was connected to that receiver.

**Comment by garethsb** [comment]
You're right, Konrad. I noted that the SDP data wasn't being parsed and merged into `transport_params` during review of #616, but we decided to take the PR with a few outstanding issues to encourage wider testing. Hopefully someone can work on this in time for the [March workshop](https://github.com/AMWA-TV/nmos-testing/discussions/642).

**Comment by garethsb** [comment]
Resolved by #656.
