### ISSUE TITLE
Build Docker container image with an initial copy of the specs for all the auto tests

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#661]
To support deployment in environments without an internet connection, it would be helpful if the Docker image could run without using git to clone the spec repos. Could a copy of the current state of these repos be included in the image at the point that it's built?

The testing tool should continue to warn that the specs are stale (and ideally how many days/months/years stale!) - perhaps even in the UI as well as the log.

The spec repos are not huge in any case, but perhaps we could avoid bloating the container unnecessarily by trimming down the repo contents included in the image to only the `APIs` directories for each branch?

**Comment by garethsb** [comment]
Could this be done simply by scripting running the testing tool once, thinning out the repos and then `docker commit` to add a new layer to the image to be pushed?

**Comment by garethsb** [comment]
https://github.com/AMWA-TV/nmos-testing/blob/8f8964d53f10c057375482fcffbb1bb353193734/nmostesting/NMOSTesting.py#L605

could be updated with `multi_options` specifying `--depth 1` and `--no-tags` and `--no-checkout` and then the code could fetch only those branches that correspond to each of the `SPECIFICATIONS` requested `versions`...

**Comment by peterbrightwell** [comment]
This is a good idea

**Comment by garethsb** [comment]
Good feedback and use case from a workshop participant:
> We'd like to run this unattended/automated as part of the overnight test cycle.  A mode of operation where the testing tool does not have to be connected to the internet to download the latest tests would be helpful.  We'd wish to manage the download of the 'latest' test suite ourselves.  What we need to do is have different versions of the test suite so that we can then have managed regression testing.
