### ISSUE TITLE
Crash when node fails to attempt to register under IS-04 v1.2

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#67]
There was another registry running on the subnet when I started the test, which explains why it didn't register, but crashing is never good.  ;-)

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/hbv-bld1/bt/git/nmos-testing/nmos-test.py", line 218, in index_page
>     raise ex
>   File "/home/hbv-bld1/bt/git/nmos-testing/nmos-test.py", line 215, in index_page
>     result = test_obj.run_tests(test_selection)
>   File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 125, in run_tests
>     self.execute_tests(test_name)
>   File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 98, in execute_tests
>     self.result.append(method())
>   File "/home/hbv-bld1/bt/git/nmos-testing/IS0401Test.py", line 101, in test_01
>     return test.FAIL("Node did not attempt to register with the registry advertised on {}.".format(default_ip))
> NameError: name 'default_ip' is not defined

I'm running commit 009b81be3c7be40793f853ea3bd55f3e59d93722.

**Comment by billt-hlit** [comment]
Replacing "default_ip" with "self.default_ip" everywhere it appears in IS0401Test.py seems to fix the crash.

**Comment by andrewbonney** [comment]
I'm struggling to find the following error message at that commit ID:
`return test.FAIL("Node did not attempt to register with the registry advertised on {}.".format(default_ip))`

Instead it should be:
`return test.FAIL("Node did not attempt to register with the advertised registry.")`

Do you have a modified local copy of the code?

**Comment by billt-hlit** [comment]
D'oh! Yes, sorry, the problem was my fault to begin with. I must have changed that line to do some debugging.
