### ISSUE TITLE
check_matching_resource checking the wrong thing?

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#68]
As of commit c18cc3f357be9deb81f85ff35378519fb2498aec, nmos-cpp-node from the sony/nmos-cpp project started failing several unit tests, starting with test_04 ("Node can register a valid Node..."), with the message "Node API JSON does not match data in registry...". Investigating further, it appears that left-hand side of the comparison has a whole lot more data than the right-hand side and that limiting the data being compared make the tests succeed. In particular, if I change line 195 from `elif reg_resource != node_resources[resource]:` to `elif reg_resource[1]['payload']['data'] != node_resources[resource]:`, the tests pass.

Does that seem like a reasonable fix, or is there something more subtle going on here?

[edit: my original proposed fix would break the test at line 193]

**Comment by andrewbonney** [comment]
I believe https://github.com/AMWA-TV/nmos-testing/pull/69 should fix this, but I need to give it a test before merging in. Thanks for spotting it.
