### ISSUE TITLE
Test incorrectly check for hostname versus IP address

### ISSUE THREAD

**Issue by alabou** [AMWA-TV/nmos-testing#686]
https://github.com/AMWA-TV/nmos-testing/blob/7532329785f71a99066aa2a3e41d5dc62fd087ad/nmostesting/suites/IS0401Test.py#L1257

                if href.startswith("https://") and urlparse(href).hostname[-1].isdigit():
                    service_href_hostname_warn = True

A valid hostname may terminate by a digit, so testing hostname[-1].isdigit() is incorrect. Proper verification of an IPv4 and IPv6 address pattern is required. The current code would reject hostname "foo1" which is an incorrect behavior as "foo1" is a valid hostname.

https://github.com/AMWA-TV/nmos-testing/blob/e6cb83f5c1625ac21ddf7aaf7ee8531e66a0592b/nmostesting/suites/IS0402Test.py has the same issue.

**Comment by garethsb** [comment]
Should be using `ipaddress` module that is already used elsewhere in the testing tool. 

https://docs.python.org/3/library/ipaddress.html#ipaddress.ip_address

**Comment by alabou** [comment]
Our devices are named with a number suffix and we fail actual tests :(

**Comment by garethsb** [comment]
> The current code would reject hostname "foo1" which is an incorrect behavior as "foo1" is a valid hostname.

To be fair, what is being checked in these cases ought to be the fully qualified host name,  like `foo1.example.com` or `foo1.local` NOT a bare hostname.

**Comment by alabou** [comment]
RFC 3986 about URI which which URL should derive from indicates "This specification does not mandate a particular registered name lookup technology and therefore does not restrict the syntax of reg-name beyond what is necessary for interoperability.  Instead, it delegates the issue of registered name syntax conformance to the operating system of each application performing URI resolution, and that operating system decides what it will allow for the purpose of host identification."

Requiring foo1.local or a fully qualified name including the domain instead of just foo1 would require registering multiple services because users of the service may resolve using mDNS or DNS or LLMNR or /etc/hosts ... I would rather use the less restrictive approach of requiring the hostname to not be an IP address.

**Comment by garethsb** [comment]
@alabou were you able to confirm that #687 resolved your issue?

**Comment by alabou** [comment]
Yes #687 fix this issue but we stumbled on the next issue https://github.com/AMWA-TV/nmos-testing/issues/689 where the test assumes the protocol of a given service would match self.protocol.
