### ISSUE TITLE
[BCP-003-01] Mock CRL and OCSP servers should be in DNS zone file?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#693]
The testing tool includes mock CRL and OCSP servers. These get started up for all test suites, both IS-04-01, etc. and the BCP-003-01 test suite itself.

The README at https://github.com/AMWA-TV/nmos-testing/blob/master/test_data/BCP00301/README.md#hosts-files suggests adding 'crl.testsuite.nmos.tv' to the device-under-test's _hosts_ file, but when the testing tool is run in unicast DNS-SD mode, so the mock DNS server is running, the entry for this could just be added to the _test_data/core/dns_base.zone_, couldn't it? The OCSP server hostname ought to be added to README and zonefile as well.

**Comment by andrewbonney** [comment]
That sounds reasonable. I can only assume we suggested doing it this way to reduce coupling and make it (potentially) easier to debug if unicast DNS-SD wasn't already in use.

**Comment by lo-simon** [comment]
Add the following to the zone file (nmos-testing\test_data\core\dns_base.zone)

> crl.{{ domain }}. IN  A     {{ ip_address }}
> ocsp.{{ domain }}. IN  A     {{ ip_address }}

**Comment by garethsb** [comment]
Resolved by #696.
