### ISSUE TITLE
IS-05 Controller (IS-04 is same), Test Selection "all:Run all tests in the suit" , got Error: 'IS0503Test' object has no attribute 'name'

### ISSUE THREAD

**Issue by Gunterwa** [AMWA-TV/nmos-testing#698]
I guess there is some config file need to be modified before get started on testing, appreciate anyone can ring me a bell .(.

**Comment by garethsb** [comment]
Do you have `ENABLE_HTTPS = True` in the config? This is not working for Controller testing yet (#688) and won't be used for JT-NM Tested August 2022.

If that's not the case, please share more about your config and test parameters/environment.

**Comment by Gunterwa** [comment]
Thanks for quick response, let me check all the configuration files first...

**Comment by Gunterwa** [comment]
> Do you have `ENABLE_HTTPS = True` in the config? This is not working for Controller testing yet (#688) and won't be used for JT-NM Tested August 2022.
> 
> If that's not the case, please share more about your config and test parameters/environment.

I use local installation on Ubuntu 22.04, in a linux contain (LXC). 
I configured "CONFIG.ENABLE_HTTPS = True" in UserConfig.py which may overwrite the corresponding items in "Config.py". All other config files are default.
In the end of "nmos-test-launch.log" can you see the access log as well, those would be log for the screen capture "Error msg on NMOS test web.jpg".

![Error msg on NMOS Test web](https://user-images.githubusercontent.com/49436510/183009230-1af73b04-e45d-43dd-b2b6-84348316e1f0.jpg)
![NMOS Controller Testing Facade web](https://user-images.githubusercontent.com/49436510/183009257-d2d48016-2781-4a43-9ec0-09cea3e3a74e.jpg)
[nmos-test-launch.log](https://github.com/AMWA-TV/nmos-testing/files/9265648/nmos-test-launch.log)
[nmos-testing-facade-launch.log](https://github.com/AMWA-TV/nmos-testing/files/9265649/nmos-testing-facade-launch.log)

**Comment by garethsb** [comment]
Ok. As I mentioned, `CONFIG.ENABLE_HTTPS = True` is not supported for Controller testing yet. Controllers can only be tested with HTTP mode for the moment.

**Comment by Gunterwa** [comment]
> Ok. As I mentioned, `CONFIG.ENABLE_HTTPS = True` is not supported for Controller testing yet. Controllers can only be tested with HTTP mode for the moment.

Sure, I did tried HTTP mode with "ENABLE_HTTPS = False" in "Config.py" and removed UserConfig.py... got same error.

**Comment by Gunterwa** [comment]
> Ok. As I mentioned, `CONFIG.ENABLE_HTTPS = True` is not supported for Controller testing yet. Controllers can only be tested with HTTP mode for the moment.

Yes, change to HTTP mode and restart LXC got the tester works, thanks!
<img width="1266" alt="Screen Shot 2022-08-05 at 15 22 08" src="https://user-images.githubusercontent.com/49436510/183024213-c164ed71-7e40-46ad-8cdb-5cdb60d92e33.png">

**Comment by garethsb** [comment]
Great! Thanks for reporting back.

Leaving open until issue with secure testing resolved. @jonathan-r-thorpe

**Comment by garethsb** [comment]
Resolved by #711. 🤞
