### ISSUE TITLE
Running other tests after IS-08 test with API Selector fails

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos-testing#702]
In IS-08, it is possible to have an "API selector" as an extra level in the URL. When you select the IS-08 test from the drop down, an extra box appears to allow you to enter this.

If you enter something, and then switch to another test (e.g. IS-04), then run, the test fails because it tries to include the extra URL level, even though (a) this isn't legal in IS-04 and (b) the box is no longer displayed.

For the opposite reason, re-running IS-08 tests from the results page (as is possible for the other tests) fails, because the "API selector" is not available to the results page, so it tries to re-run the requested tests with no selector set.

**Comment by garethsb** [comment]
@firthmj, please would you verify?
