### ISSUE TITLE
IS-05-02 Test 17 fails when no PTP locking

### ISSUE THREAD

**Issue by robert-pot** [AMWA-TV/nmos-testing#719]
In test 17 a check is done if the ts-refclk is correct in the sdp.
when there is no PTP locking the SDP file contains something like:
   a=ts-refclk:localmac=00-b0-09-02-b3-9c

In the test the string "localmac=" is removed with the following command:
   sdp_mac = ts_refclk.group(1).strip("localmac=").lower()

But this will also remove the last 'c' character from the mac address, same error if it would end with a 'a' character.

Please change this with something like:
   sdp_mac = ts_refclk.group(1)[9:].lower()

**Comment by garethsb** [comment]
Yep. Someone obviously misunderstood the meaning of `strip`... probably common given the explanation for `lstrip` and introduction of `removeprefix` in Python 3.9...

https://docs.python.org/3/library/stdtypes.html#str.lstrip
