### ISSUE TITLE
CORS is checked without Origin header

### ISSUE THREAD

**Issue by orryverducci** [AMWA-TV/nmos-testing#722]
I've discovered an issue while testing my application with the NMOS API Testing Tool. In my case I was using the IS-04 Node API test suite.

The testing tool checks for the presence of CORS headers (specifically Access-Control-Allow-Origin) while testing API's, and fails the tests if the header is not in the response. However it doesn't send an Origin header in the request to the API, which is required by the [CORS specification](https://fetch.spec.whatwg.org/#http-requests) for the request to be a valid CORS request. It states:

> A CORS request is an HTTP request that includes an '[Origin](https://fetch.spec.whatwg.org/#http-origin)' header.

This is an issue as some servers/frameworks (ASP.NET in my case) won't send CORS headers in their response if the Origin header is absent, as by the CORS specification a request without an Origin header isn't a CORS request and so doesn't require a CORS response.

Therefore the testing tool should send an Origin header when testing these APIs, otherwise apps built on these frameworks unfairly fail the test due to the frameworks believing the testing tools doesn't participate in the CORS protocol.

This may be a result of what appears to me to be an oversight in the NMOS specifications, as they state for server side implementations that "all NMOS APIs MUST implement valid CORS HTTP headers in responses to all requests", but don't require clients to do the same.

**Comment by garethsb** [comment]
Thanks, @orryverducci, your analysis looks correct to me, including the comment about the specs' Server Side Implementation Notes and your proposed fix - adding `Origin: null` to all requests could be enough?

**Comment by orryverducci** [comment]
> adding `Origin: null` to all requests could be enough?

Yes, I think adding `Origin: null` to all requests will be sufficient. Just tried it with ASP.NET and it happily accepts the null origin as a valid CORS request, returning the required CORS headers back.

Do you think it'd also be worth me opening an issue against the specs regarding this?

**Comment by garethsb** [comment]
@orryverducci I'm closing this as completed after merging #724, but yes, I think it is worth reporting at https://github.com/AMWA-TV/is-04/issues that the language "all NMOS APIs MUST implement valid CORS HTTP headers in responses to all requests" is misleading. It's trying to say that NMOS API servers MUST support CORS and thus respond with the correct response headers when the client makes a CORS request.
