### ISSUE TITLE
IS-05 test needed: Verify that each sender's and receiver's staged transport parameters meet the constraints

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#77]
I just got bitten by this -- my staged parameters violate the constraints, and since the API client didn't specify any transport parameters, the server rejected the request as invalid. Oops.

I don't think you can do the same thing for the active parameters, however -- a parameter might be constrained to "auto", but the active parameter has to reflect the actual value.

**Comment by garethsb-sony** [comment]
Nice enhancement, since as you say it's *implied* by the spec since a request with no transport params is valid.

Your NMOS library probably ought to provide a way for you to validate that internally too...

**Comment by billt-hlit** [comment]
More on this: I was incorrectly setting the staged receivers' multicast_ip to "auto" and the tests didn't detect the failure to match the schema.

**Comment by andrewbonney** [comment]
I was just going to take a look at this, but unless I'm misunderstanding it's meant to be covered by test_09 and test_10 in IS0501. I'll see if those tests are functioning as expected, but I'd appreciate a confirmation of whether those tests look like they should be achieving this.

**Comment by andrewbonney** [comment]
Looking again, that's not the case. I'll try and add something that does this.

**Comment by andrewbonney** [comment]
Ok, a further looks suggests this should be what test_15/16 do, but I can replicate the issue with multicast_ip set to auto, so something's clearly not right. These tests are also due an update for testing v1.1+

**Comment by andrewbonney** [comment]
Right... This looks like it could be the issue. https://github.com/Julian/jsonschema/blob/fa72031da22792778d501fe3002ec3609e4a62c0/docs/validate.rst#validating-formats

> By default, no validation is enforced, but optionally, validation can be enabled by hooking in a format-checking object into an IValidator.

**Comment by andrewbonney** [comment]
@billt-hlit could you see if https://github.com/AMWA-TV/nmos-testing/pull/153 resolves this issue?

**Comment by andrewbonney** [comment]
This closed automatically on merge, but please re-open if it hasn't resolved the problem.

**Comment by billt-hlit** [comment]
It now correctly detects that constraint failure. Thanks!

Incidentally and presumably relatedly, the test suite is now catching that we're using an understore in our hostname in the IS-04 "self" endpoint. That's a bit inconvenient for us (our machines have always had that underscore). I'm wondering if the hostname format really needs to be enforced that closely.

**Comment by andrewbonney** [comment]
Ok, Gareth mentioned that sort of issue previously. I'll modify the format checker to skip the hostname checks.

**Comment by garethsb-sony** [comment]
Ha ha, yes - https://github.com/AMWA-TV/nmos-testing/pull/153#pullrequestreview-210642579, we didn't have to wait long, Andrew. :-) Thanks for sorting this.
