### ISSUE TITLE
Ramlfications fails to parse IS-07 global types

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#78]
The IS-07 spec appears to use valid RAML 1.0, but ramlfications (being a 0.8 library) can't quite handle the way they're written. As such several tests appear as 'manual' when they should work.

**Comment by mjeras** [comment]
I've just noticed this issue separately today (wasn't doing automated testing of IS-07 before) and it is great that you prepared the fix, thank you very much for that. However, I don't  see the change in master so I assume it is in one of the open pull requests - when do you think those will be merged? Anything I can do to help?

**Comment by andrewbonney** [comment]
It's just waiting for a review (which hopefully won't take long), but if you can confirm it works for you then that's useful to prove it. Unfortunately I don't have an 07 implementation here so I'm just going based off what I saw at the workshop.

Slightly related, I put an issue in here https://github.com/AMWA-TV/nmos-event-tally/issues/19 for another problem that the test suite caught. Hopefully it's a quick fix.

**Comment by mjeras** [comment]
I'll pull the commit from the pull request now and give it a quick test and will also fix the RAML issue you created.
