### ISSUE TITLE
IS-04 test_28 (BCP-002-02) executed if BCP-002-01 is implemented

### ISSUE THREAD

**Issue by gagnonfranck** [AMWA-TV/nmos-testing#787]
If the device implements the group hint BCP-002-01 (test_23) but not BCP-002-02 (test_28) will fail
![2023-04-18_16-07](https://user-images.githubusercontent.com/38817592/232895019-61daf155-043e-4433-990c-64849d82df38.png)

**Comment by garethsb** [comment]
Group Hint Tags are only intended to be used on Sender and Receiver resources, not Devices. Similarly, Asset Tags are only intended to be used on Node and Device resources, not Senders and Receivers.

These test cases are independent.

test_23 applies to Sender and Receiver resources and will pass if Group Hint Tags are present, fail if they are not present, and should be unaffected by any other Tags on these resources.

test_28 applies to Node and Device Resources and will pass if Asset Tags are present, fail if they are not present, and should be unaffected by any other Tags on these resources.

**Comment by gagnonfranck** [comment]
Thanks for the explanation

**Comment by garethsb** [comment]
@gagnonfranck If you have an example of a Node that fails either test case unexpectedly, please share the `tags` properties from the Node, Device, Sender and Receiver resources here and I'll investigate.
