### ISSUE TITLE
[IS-11] Fix test 0.1 to look  at  all  the  devices  exposing  the  IS-11 API

### ISSUE THREAD

**Issue by gwgeorgea** [AMWA-TV/nmos-testing#791]
Based on
https://github.com/AMWA-TV/nmos-testing/pull/761#discussion_r1118725541
The spec (0.9) was change in response. The test needs to be change accordingly.

**Comment by N-Nagorny** [comment]
@garethsb, could you please close it? It's covered by https://github.com/AMWA-TV/nmos-testing/pull/806/?
