### ISSUE TITLE
AttributeError: 'functools._lru_cache_wrapper' object has no attribute '__kwdefaults__'

### ISSUE THREAD

**Issue by 1Julian2** [AMWA-TV/nmos-testing#828]
Hello,
I have a problem to start the tool.
I use Python 3.11. 
Short info: I have already used the program before this error and at that time it worked fine. 
No matter which startup I use (Via the IDE, as python-command, or as Non-Interactive mode), this error message always appears.
Thanks for help.

**Comment by garethsb** [comment]
Sorry, we triaged this in AMWA Slack a few days ago, but didn't cross post to GitHub... https://amwatv.slack.com/archives/CJSQXMGV9/p1691400064650139

Looks like they added lru_cache in 0.73.0 a few days ago: https://github.com/python-zeroconf/python-zeroconf/pull/1211

This broke our monkeypatch that is required to allow us to register the strictly-invalid `_nmos-registration._tcp` service type: https://github.com/AMWA-TV/nmos-testing/pull/812

Appears we're not the only people to have used that: https://github.com/python-zeroconf/python-zeroconf/issues/1046

I'm hopeful that this PR will make the monkeypatch unnecessary, we can finally just explicitly pass `strict=False` for our old service type. https://github.com/python-zeroconf/python-zeroconf/pull/1215

For now, please pin the required version to 0.72.0, but the new zeroconf maintainer is quite responsive, so I hope the proposed fix will be merged and published soon, and then I'll fix up nmos-testing.

**Comment by garethsb** [comment]
https://github.com/python-zeroconf/python-zeroconf/releases/tag/0.75.0 is now available with the fix, so I'll integrate this soon
