### ISSUE TITLE
Latest version of python-zeroconf requires bump of mimimum Python version to 3.7

### ISSUE THREAD

**Issue by jonathan-r-thorpe** [AMWA-TV/nmos-testing#830]
Attempting to use test suites that use the latest version of python-zeroconf when using the current minimum Python requirement for NMOS Testing (Python 3.6) leads to aysncio errors, as zeroconf now requires a minimum of Python 3.7.

Error reported:
`AttributeError: module 'asyncio' has no attribute 'get_running_loop'`

Suggested solution is to bump minimum Python version to 3.7 perhaps as part of #829 PR?

**Comment by garethsb** [comment]
Python 3.7 is also already end of life, so I'll bump to 3.8 in the PR as you suggest. Thanks, Jonathan!
