### ISSUE TITLE
Exhaustive testing is exhausting

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#84]
Test 26 (immediate receiver activations) takes 48 seconds to test my 80 receivers (and mine is a small system!). Maybe some of these tests just configure a random sampling of the receivers and time out after, say, 10 receivers? Possibly there could be an option on the front page to control this.

**Comment by andrewbonney** [comment]
Sounds sensible to me. I'll look at imposing some limits on things.

**Comment by billt-hlit** [comment]
That looks good! I see tests 27 and 28 take about 2.5 seconds per iteration (why relative activations take a half second longer than absolute is mysterious, but there it is).

I take it that the test harness does not watch for changes to Config.py? That came as a surprise to me.

**Comment by andrewbonney** [comment]
I don't believe it will 'watch' for anything anymore. The change to use Flask's production rather than debug mode will have modified that, and was necessary to make the multi-registry tests work reliably.

**Comment by garethsb-sony** [comment]
> I don't believe it will 'watch' for anything anymore.

Oh, I'd noticed that, and hadn't investigated why. That's a shame. :-(
