### ISSUE TITLE
Ensure all Node resources use unique UUIDs

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#97]
Ideally we'd also test that two different Nodes of the same type abide by this, but that's harder at present.

**Comment by billt-hlit** [comment]
Hi, Andrew. Looking at the new test, wouldn't it be more efficient to use a dictionary rather than an array? The current implementation is going to take a lot of time to search the array for IDs.

**Comment by andrewbonney** [comment]
https://github.com/AMWA-TV/nmos-testing/pull/105
